Repository codesquad-members-2022/todo-list, pull requests merged in 2022-04, with the labels that each got.

#22 [Team-05 BE nathan & 피오] 프로젝트 초기 세팅 및 MySQL 구동
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  backend/.gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/team05/todolist/TodoListApplication.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/team05/todolist/TodoListApplicationTests.java
Labels: review-BE

#29 [team29][FE] 프로젝트 기본 구성 설정
  .eslintrc.json
  .gitignore
  .prettierrc
  .scss-lint.yml
  babel.config.json
  index.html
  package-lock.json
  package.json
  src/utils/utils.js
  styles/main.scss
  webpack.config.js
Labels: review-FE

#57 [Team-25] [FE] TODO LIST 1주차 첫 번째 PR
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .prettierrc
  README.md
  babel.config.json
  db.json
  index.html
  nodemon.json
  package-lock.json
  package.json
  server.js
  src/js/app.js
  src/style/style.scss
  webpack.config.cjs
Labels: review-FE

#59 [team06] [iOS] Card 생성에 대한 모델 구현 및 CardBoard 뷰 설계
  .gitignore
  README.md
  TodoList/TodoList.xcodeproj/project.pbxproj
  TodoList/TodoList.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  TodoList/TodoList.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  TodoList/TodoList/AppDelegate.swift
  TodoList/TodoList/Assets.xcassets/AccentColor.colorset/Contents.json
  TodoList/TodoList/Assets.xcassets/AppIcon.appiconset/Contents.json
  TodoList/TodoList/Assets.xcassets/Contents.json
  TodoList/TodoList/Base.lproj/LaunchScreen.storyboard
  TodoList/TodoList/Base.lproj/Main.storyboard
  TodoList/TodoList/CardBoardViewController.swift
  TodoList/TodoList/Info.plist
  TodoList/TodoList/SceneDelegate.swift
  TodoList/TodoList/TodoStoryboard.storyboard
  TodoList/TodoList/TodoViewController.swift
  TodoList/TodoList/domain/Card.swift
  TodoList/TodoList/domain/CardBoard.swift
  TodoList/TodoList/domain/CardFactory.swift
  TodoList/TodoList/domain/CardUsable.swift
  TodoList/TodoList/domain/TodoCardManager.swift
  TodoList/TodoList/domain/delegate/DoingCardDelegate.swift
  TodoList/TodoList/domain/delegate/DoneCardDelegate.swift
  TodoList/TodoListTests/TodoListTests.swift
  TodoList/TodoListUITests/TodoListUITests.swift
  TodoList/TodoListUITests/TodoListUITestsLaunchTests.swift
Labels: review-iOS

#62 [Team-27] [FE] TODO LIST 1주차 첫번째 PR
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/main-issue-template.md
  .gitignore
  README.md
  babel.config.json
  dist/js/6f340f350a61b2ce4434.png
  dist/js/814560d7909b27bfd38d.png
  dist/js/a55b9a684f4f29cfcfa1.png
  dist/js/bundle.js
  dist/js/bundle.js.map
  index.html
  package-lock.json
  package.json
  src/js/app.js
  src/js/component.js
  src/sass/main.scss
  src/sass/partials/_body.scss
  src/sass/partials/_button.scss
  src/sass/partials/_card.scss
  src/sass/partials/_header.scss
  src/sass/partials/_log.scss
  src/sass/partials/_mixins.scss
  src/sass/partials/_modal.scss
  src/sass/partials/_reset.scss
  src/sass/partials/_variable.scss
  webpack.config.js
Labels: review-FE

#43 [Team-23] [FE] 템플릿 구조 와 목데이터 렌더링
  .gitignore
  README.md
  TodoList.js
  app.js
  core/Component.js
  core/Header.js
  core/MainSection.js
  core/Store.ts
  core/TodoList.js
  header.js
  index.html
  readme.md
  styles/scss/column.scss
  styles/scss/header.scss
  styles/scss/index.scss
  styles/scss/reset.scss
Labels: review-FE

#9 [Team26 - BE] 프로젝트 초기 셋팅 및 Mock API 제공
  .gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/team26/todolist/TodolistApplication.java
  BE/src/main/java/com/team26/todolist/controller/CardController.java
  BE/src/main/java/com/team26/todolist/domain/Card.java
  BE/src/main/java/com/team26/todolist/domain/CardStatus.java
  BE/src/main/java/com/team26/todolist/dto/request/CardDeleteRequest.java
  BE/src/main/java/com/team26/todolist/dto/request/CardMoveRequest.java
  BE/src/main/java/com/team26/todolist/dto/request/CardRegistrationRequest.java
  BE/src/main/java/com/team26/todolist/dto/request/CardUpdateRequest.java
  BE/src/main/java/com/team26/todolist/dto/response/CardResponse.java
  BE/src/main/java/com/team26/todolist/service/CardService.java
  BE/src/main/java/com/team26/todolist/service/CardServiceMock.java
  BE/src/main/resources/application.properties
  BE/src/test/java/com/team26/todolist/TodolistApplicationTests.java
  README.md
Labels: review-BE

#58 [Team-07][iOS] 메인 화면 뷰 구현
  README.md
  be/README.md
  ios/.gitignore
  ios/README.md
  ios/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  ios/ToDoListApp/ToDoListApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/ToDoListApp/ToDoListApp/AppDelegate.swift
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/AccentColor.colorset/Contents.json
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/Contents.json
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/InspectorButton.imageset/Contents.json
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/InspectorButton.imageset/InspectorButton.png
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/InspectorButton.imageset/InspectorButton@2x.png
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/InspectorButton.imageset/InspectorButton@3x.png
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/addButton.imageset/Contents.json
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/addButton.imageset/addButton.png
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/addButton.imageset/addButton@2x.png
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/addButton.imageset/addButton@3x.png
  ios/ToDoListApp/ToDoListApp/Base.lproj/LaunchScreen.storyboard
  ios/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  ios/ToDoListApp/ToDoListApp/Controller/DoneViewController.swift
  ios/ToDoListApp/ToDoListApp/Controller/InProgressViewController.swift
  ios/ToDoListApp/ToDoListApp/Controller/MainViewController.swift
  ios/ToDoListApp/ToDoListApp/Controller/ToDoViewController.swift
  ios/ToDoListApp/ToDoListApp/Info.plist
  ios/ToDoListApp/ToDoListApp/Model/CellData.swift
  ios/ToDoListApp/ToDoListApp/Model/TableViewDataSource.swift
  ios/ToDoListApp/ToDoListApp/SceneDelegate.swift
  ios/ToDoListApp/ToDoListApp/View/CustomTableViewCell.swift
  ios/ToDoListApp/ToDoListApp/View/TableTitleView.swift
  ios/ToDoListApp/ToDoListApp/View/TitleView.swift
Labels: review-iOS

#40 [team-03][BackEnd] todo-list 1주차 #1
  README.md
  backend/README.md
  backend/todo-app/.gitignore
  backend/todo-app/build.gradle
  backend/todo-app/gradle/wrapper/gradle-wrapper.jar
  backend/todo-app/gradle/wrapper/gradle-wrapper.properties
  backend/todo-app/gradlew
  backend/todo-app/gradlew.bat
  backend/todo-app/settings.gradle
  backend/todo-app/src/main/java/team03/todoapp/TodoAppApplication.java
  backend/todo-app/src/main/java/team03/todoapp/controller/CardsResponse.java
  backend/todo-app/src/main/java/team03/todoapp/controller/MockController.java
  backend/todo-app/src/main/resources/application.properties
  backend/todo-app/src/test/java/team03/todoapp/TodoAppApplicationTests.java
Labels: review-BE

#34 [Team04][BE] 루이 & Hwi - 1주차 첫 번째 PR입니다.
  BackEnd/.gitignore
  BackEnd/HELP.md
  BackEnd/build.gradle
  BackEnd/gradle/wrapper/gradle-wrapper.jar
  BackEnd/gradle/wrapper/gradle-wrapper.properties
  BackEnd/gradlew
  BackEnd/gradlew.bat
  BackEnd/settings.gradle
  BackEnd/src/main/java/todo/list/ListApplication.java
  BackEnd/src/main/java/todo/list/controller/ActivityLogController.java
  BackEnd/src/main/java/todo/list/domain/Action.java
  BackEnd/src/main/java/todo/list/domain/ActivityLog.java
  BackEnd/src/main/java/todo/list/domain/Card.java
  BackEnd/src/main/java/todo/list/domain/CardStatus.java
  BackEnd/src/main/java/todo/list/repository/ActivityLogRepository.java
  BackEnd/src/main/java/todo/list/service/ActivityLogDto.java
  BackEnd/src/main/java/todo/list/service/ActivityLogService.java
  BackEnd/src/main/resources/application.properties
  BackEnd/src/main/resources/data.sql
  BackEnd/src/main/resources/schema.sql
  BackEnd/src/test/java/todo/list/ListApplicationTests.java
  README.md
Labels: review-BE

#50 [team-01][BE] 1주차 1회 PR
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/codesquad/be/todoserver/TodoserverApplication.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
  BE/src/test/java/codesquad/be/todoserver/TodoserverApplicationTests.java
  README.md
Labels: review-BE

#63 [Team-20] 1주차 - 협업방식, 개발환경, 프로젝트 구조 설계
  .gitignore
  .prettierrc
  README.md
  client/babel.config.json
  client/dist/app.bundle.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/js/app.js
  client/public/js/controller/Controller.js
  client/public/js/model/Store.js
  client/public/js/tempStorage.js
  client/public/js/utils/helpers.js
  client/public/js/views/View.js
  client/public/js/views/aside/AsideView.js
  client/public/js/views/card/CardsView.js
  client/public/js/views/columns/ColumnsView.js
  client/public/js/views/header/HeaderView.js
  client/public/js/views/main/MainView.js
  client/public/style/main.scss
  client/webpack.config.js
  server/DB/db.json
  server/app.js
  server/package-lock.json
  server/package.json
Labels: review-FE

#25 [BE: team-11 hoo & Riako] todo-list 프로젝트 생성 및 API 문서 작성
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  backend/.gitignore
  backend/.idea/.gitignore
  backend/.idea/compiler.xml
  backend/.idea/gradle.xml
  backend/.idea/jarRepositories.xml
  backend/.idea/misc.xml
  backend/.idea/vcs.xml
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/hooria/todo/TodoApplication.java
  backend/src/main/java/com/hooria/todo/config/SwaggerConfig.java
  backend/src/main/java/com/hooria/todo/controller/ActivityLogController.java
  backend/src/main/java/com/hooria/todo/controller/CardController.java
  backend/src/main/java/com/hooria/todo/controller/MemberController.java
  backend/src/main/java/com/hooria/todo/domain/ActivityLog.java
  backend/src/main/java/com/hooria/todo/domain/Card.java
  backend/src/main/java/com/hooria/todo/domain/Member.java
  backend/src/main/java/com/hooria/todo/repository/ActivityLogRepository.java
  backend/src/main/java/com/hooria/todo/repository/CardRepository.java
  backend/src/main/java/com/hooria/todo/repository/MemberRepository.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/hooria/todo/DataSourceTest.java
  backend/src/test/java/com/hooria/todo/TodoApplicationTest.java
  backend/src/test/java/com/hooria/todo/repository/ActivityLogRepositoryTest.java
  backend/src/test/java/com/hooria/todo/repository/CardRepositoryTest.java
  backend/src/test/java/com/hooria/todo/repository/MemberRepositoryTest.java
  backend/src/test/resources/data.sql
  backend/src/test/resources/schema.sql
  backend/system.properties
  iOS/README.md
  iOS/todo-list/todo-list.xcodeproj/project.pbxproj
  iOS/todo-list/todo-list.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/todo-list/todo-list.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/todo-list/todo-list/AppDelegate.swift
  iOS/todo-list/todo-list/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/todo-list/todo-list/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/todo-list/todo-list/Resource/Assets.xcassets/Contents.json
  iOS/todo-list/todo-list/Resource/Base.lproj/LaunchScreen.storyboard
  iOS/todo-list/todo-list/Resource/Base.lproj/Main.storyboard
  iOS/todo-list/todo-list/SceneDelegate.swift
  iOS/todo-list/todo-list/ViewController/ViewController.swift
  iOS/todo-list/todo-list/configuration/Info.plist
  iOS/todo-list/todo-listTests/todo_listTests.swift
  iOS/todo-list/todo-listUITests/todo_listUITests.swift
  iOS/todo-list/todo-listUITests/todo_listUITestsLaunchTests.swift
Labels: review-BE

#38 [team-12][BE] 현재까지의 진행사항 PR
  README.md
  be/.gitignore
  be/.gitkeep
  be/.idea/.gitignore
  be/HELP.md
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/com/ijava/todolist/TodolistApplication.java
  be/src/main/java/com/ijava/todolist/card/controller/CardController.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardResponse.java
  be/src/main/java/com/ijava/todolist/card/domain/Card.java
  be/src/main/java/com/ijava/todolist/card/exception/CardNotFoundException.java
  be/src/main/java/com/ijava/todolist/card/exception/CardNotSavedException.java
  be/src/main/java/com/ijava/todolist/card/exception/CardRuntimeException.java
  be/src/main/java/com/ijava/todolist/card/repository/CardRepository.java
  be/src/main/java/com/ijava/todolist/card/repository/JdbcCardRepository.java
  be/src/main/java/com/ijava/todolist/card/service/CardService.java
  be/src/main/java/com/ijava/todolist/column/controller/ColumnController.java
  be/src/main/java/com/ijava/todolist/column/controller/dto/ColumnResponse.java
  be/src/main/java/com/ijava/todolist/column/domain/Column.java
  be/src/main/java/com/ijava/todolist/column/repository/ColumnRepository.java
  be/src/main/java/com/ijava/todolist/column/repository/JDBCColumnRepository.java
  be/src/main/java/com/ijava/todolist/column/service/ColumnService.java
  be/src/main/java/com/ijava/todolist/exception/GlobalExceptionHandler.java
  be/src/main/java/com/ijava/todolist/exception/GlobalRuntimeException.java
  be/src/main/resources/application.yml
  be/src/main/resources/logback.xml
  be/src/main/resources/sql/ddl-h2.sql
  be/src/main/resources/sql/test/column-dml-h2.sql
  be/src/test/java/com/ijava/todolist/TodolistApplicationTests.java
  be/src/test/java/com/ijava/todolist/card/controller/CardControllerTest.java
  be/src/test/java/com/ijava/todolist/card/repository/CardRepositoryTest.java
  be/src/test/java/com/ijava/todolist/card/service/CardServiceTest.java
  be/src/test/java/com/ijava/todolist/column/controller/ColumnControllerTest.java
  be/src/test/java/com/ijava/todolist/column/repository/ColumnRepositoryTest.java
  be/src/test/java/com/ijava/todolist/column/service/ColumnServiceTest.java
  ios/.gitkeep
Labels: review-BE

#44 [BE][team-10] Todo-list 1주차 PR #1
  .gitignore
  BE/.gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/kr/codesquad/todolist/controller/mockupController.java
  BE/src/main/java/kr/codesquad/todolist/domain/Card.java
  BE/src/main/java/kr/codesquad/todolist/dto/CardDto.java
  BE/src/main/java/kr/codesquad/todolist/dto/CardResponse.java
  BE/src/main/java/kr/codesquad/todolist/repository/CardRepository.java
  BE/src/main/java/kr/codesquad/todolist/repository/JdbcCardRepository.java
  BE/src/main/java/kr/codesquad/todolist/service/CardService.java
  BE/src/main/java/kr/codesquad/todolist/todolistApplication.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/kr/codesquad/todolist/repository/JdbcCardRepositoryTest.java
  BE/src/test/java/kr/codesquad/todolist/todolistApplicationTests.java
  README.md
Labels: review-BE

#49 [Team-09][BE] 1주차 # PR1 - Jun & Bong
  .idea/.gitignore
  .idea/compiler.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/runConfigurations.xml
  .idea/todo-list.iml
  .idea/vcs.xml
  backend/.gitignore
  backend/.gradle/7.4.1/checksums/checksums.lock
  backend/.gradle/7.4.1/checksums/md5-checksums.bin
  backend/.gradle/7.4.1/checksums/sha1-checksums.bin
  backend/.gradle/7.4.1/dependencies-accessors/dependencies-accessors.lock
  backend/.gradle/7.4.1/dependencies-accessors/gc.properties
  backend/.gradle/7.4.1/executionHistory/executionHistory.bin
  backend/.gradle/7.4.1/executionHistory/executionHistory.lock
  backend/.gradle/7.4.1/fileChanges/last-build.bin
  backend/.gradle/7.4.1/fileHashes/fileHashes.bin
  backend/.gradle/7.4.1/fileHashes/fileHashes.lock
  backend/.gradle/7.4.1/fileHashes/resourceHashesCache.bin
  backend/.gradle/7.4.1/gc.properties
  backend/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  backend/.gradle/buildOutputCleanup/cache.properties
  backend/.gradle/buildOutputCleanup/outputFiles.bin
  backend/.gradle/file-system.probe
  backend/.gradle/vcs-1/gc.properties
  backend/.idea/.gitignore
  backend/.idea/compiler.xml
  backend/.idea/intellij-javadocs-4.0.1.xml
  backend/.idea/jarRepositories.xml
  backend/.idea/misc.xml
  backend/.idea/vcs.xml
  backend/build.gradle
  backend/build/resources/main/application.yml
  backend/build/tmp/compileJava/previous-compilation-data.bin
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/example/backend/BackendApplication.java
  backend/src/main/java/com/example/backend/controller/card/CardController.java
  backend/src/main/java/com/example/backend/controller/column/ColumnController.java
  backend/src/main/java/com/example/backend/controller/member/MemberRestController.java
  backend/src/main/java/com/example/backend/domain/card/Card.java
  backend/src/main/java/com/example/backend/domain/card/CardType.java
  backend/src/main/java/com/example/backend/domain/column/Column.java
  backend/src/main/java/com/example/backend/domain/member/Member.java
  backend/src/main/java/com/example/backend/repository/card/CardRepository.java
  backend/src/main/java/com/example/backend/repository/card/jdbc/CardJdbcRepository.java
  backend/src/main/java/com/example/backend/repository/column/ColumnRepository.java
  backend/src/main/java/com/example/backend/repository/column/jdbc/ColumnJdbcRepository.java
  backend/src/main/java/com/example/backend/repository/member/MemberRepository.java
  backend/src/main/java/com/example/backend/repository/member/jdbc/MemberJdbcRepository.java
  backend/src/main/java/com/example/backend/service/card/CardService.java
  backend/src/main/java/com/example/backend/service/column/ColumnService.java
  backend/src/main/java/com/example/backend/service/member/MemberService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/images/branch_strategy-01.png
  backend/src/test/java/com/example/backend/BackendApplicationTests.java
Labels: review-BE

#42 [Team 24][FE][JS&S] 1주차(수) PR
  .gitignore
  README.md
  build/babel.config.json
  build/dist/bundle.js
  build/package-lock.json
  build/package.json
  build/src/image/crossBtn.png
  build/src/image/hamburgerBtn.png
  build/src/image/plusBtn.png
  build/src/image/userImg.png
  build/src/index.html
  build/src/javascript/app.js
  build/src/stylesheet/css/action.css
  build/src/stylesheet/css/card.css
  build/src/stylesheet/css/column.css
  build/src/stylesheet/css/header.css
  build/src/stylesheet/css/index.css
  build/src/stylesheet/css/reset.css
  build/webpack.config.js
  server/data.json
  server/package-lock.json
Labels: review-FE

#56 [team-30][FE] 개발 환경 설정 및 협업방식 결정
  .gitignore
  README.md
  babel.config.json
  package-lock.json
  package.json
  src/app.js
  src/index.html
  src/reset.css
  src/style.css
  webpack.config.js
Labels: review-FE

#27 [Team 32][FE] Todo List 1주차 PR
  .eslintrc.json
  .gitignore
  .prettierrc.json
  README.md
  app.js
  babel.config.json
  components/Todo.js
  components/TodoColumn.js
  components/TodoHeader.js
  components/TodoInput.js
  constants/todos.js
  constants/users.js
  dist/bundle.js
  index.css
  index.css.map
  index.html
  package-lock.json
  package.json
  style/_alarm.scss
  style/_input.scss
  style/_mixins.scss
  style/_reset.scss
  style/_utilities.scss
  style/_variables.scss
  style/index.scss
  webpack.config.js
Labels: review-FE

#31 [team_033] 그룹 프로젝트 1주차 PR
  .github/ISSUE_TEMPLATE/--------.md
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .gitmessage.txt
  .prettierrc.json
  README.md
  babel.config.json
  client/src/assets/icon/closeIcon.svg
  client/src/assets/icon/menuIcon.svg
  client/src/assets/icon/plusIcon.svg
  client/src/assets/imoge/user img.png
  client/src/index.html
  client/src/styles/_common.scss
  client/src/styles/_variables.scss
  client/src/styles/body/_body.scss
  client/src/styles/css/main.css
  client/src/styles/css/main.css.map
  client/src/styles/css/reset.css
  client/src/styles/header/_headerBar.scss
  client/src/styles/main.scss
  client/src/styles/reset.scss
  package-lock.json
  package.json
  webpack.config.js
Labels: review-FE

#33 [Team 34] [Front] Millie & Hoi
  .gitignore
  .prettierrc
  README.md
  babel.config.json
  package-lock.json
  package.json
  src/index.html
  src/js/constants/constant.js
  src/js/index.js
  src/js/views/header.js
  src/js/views/main.js
  src/scss/base/_normalize.scss
  src/scss/base/_reset.scss
  src/scss/components/_card.scss
  src/scss/constants/_colors.scss
  src/scss/constants/_typography.scss
  src/scss/main.scss
  src/scss/mixins/_flexbox.scss
  src/scss/views/_todo.scss
  webpack.config.js
Labels: review-FE

#26 [team-17][BE] 기획서 기반 데이터베이스 및 API 설계
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  backend/.gitignore
  backend/README.md
  backend/build.gradle
  backend/diagram.drawio
  backend/docker/local-database.yml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/codesquad/todolist/TodolistApplication.java
  backend/src/main/java/com/codesquad/todolist/config/SwaggerConfig.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/codesquad/todolist/TodolistApplicationTests.java
  frontend/index.html
Labels: review-BE

#45 [team-22][FE] todo-list 1주차 - 협업전략짜기
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  front/.eslintrc.js
  front/.gitignore
  front/.prettierrc
  front/babel.config.json
  front/package-lock.json
  front/package.json
  front/postcss.config.js
  front/webpack.config.js
Labels: review-FE

#12 [Team-21 BE Ikjo & Hanse] Todo-List 프로젝트 1주차(수요일) 코드 리뷰 요청
  .gitignore
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/com/todolist/TodolistApplication.java
  BE/src/main/java/com/todolist/config/MvcConfig.java
  BE/src/main/java/com/todolist/controller/WorkController.java
  BE/src/main/java/com/todolist/domain/Category.java
  BE/src/main/java/com/todolist/domain/Work.java
  BE/src/main/java/com/todolist/domain/WorkLog.java
  BE/src/main/java/com/todolist/dto/ColumnListDto.java
  BE/src/main/java/com/todolist/dto/WorkDto.java
  BE/src/main/java/com/todolist/dto/WorkListDto.java
  BE/src/main/java/com/todolist/dto/WorkLogDto.java
  BE/src/main/java/com/todolist/dto/WorkLogListDto.java
  BE/src/main/java/com/todolist/repository/WorkLogRepository.java
  BE/src/main/java/com/todolist/repository/WorkRepository.java
  BE/src/main/java/com/todolist/service/WorkLogService.java
  BE/src/main/java/com/todolist/service/WorkService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/main/resources/static/index.html
  BE/src/test/java/com/todolist/TodolistApplicationTests.java
  FE/init.txt
  README.md
Labels: review-BE

#46 [Team-09] Kai & Pigbag _ TodoList Layout, dataFetching
  .gitignore
  To-Do_List/To-Do_List.xcodeproj/project.pbxproj
  To-Do_List/To-Do_List.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  To-Do_List/To-Do_List.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  To-Do_List/To-Do_List.xcodeproj/project.xcworkspace/xcuserdata/bagjinseob.xcuserdatad/UserInterfaceState.xcuserstate
  To-Do_List/To-Do_List.xcodeproj/xcuserdata/bagjinseob.xcuserdatad/xcschemes/xcschememanagement.plist
  To-Do_List/To-Do_List/Base.lproj/Main.storyboard
  To-Do_List/To-Do_List/ChildViewControllers/DoingTableViewController.swift
  To-Do_List/To-Do_List/ChildViewControllers/DoneTableViewController.swift
  To-Do_List/To-Do_List/ChildViewControllers/ToDoTableViewController.swift
  To-Do_List/To-Do_List/Info.plist
  To-Do_List/To-Do_List/LogTable/LogTableViewController.swift
  To-Do_List/To-Do_List/MainViewController.swift
  To-Do_List/To-Do_List/Network/HttpMethod.swift
  To-Do_List/To-Do_List/Network/NetworkError.swift
  To-Do_List/To-Do_List/Network/NetworkManager.swift
  To-Do_List/To-Do_List/SupportingFiles/AppDelegate.swift
  To-Do_List/To-Do_List/SupportingFiles/Assets.xcassets/AccentColor.colorset/Contents.json
  To-Do_List/To-Do_List/SupportingFiles/Assets.xcassets/AppIcon.appiconset/Contents.json
  To-Do_List/To-Do_List/SupportingFiles/Assets.xcassets/Contents.json
  To-Do_List/To-Do_List/SupportingFiles/Base.lproj/LaunchScreen.storyboard
  To-Do_List/To-Do_List/SupportingFiles/SceneDelegate.swift
  To-Do_List/To-Do_List/Todo.swift
  To-Do_List/To-Do_List/View/CardCell.swift
  To-Do_List/To-Do_List/View/TableViewHeader.swift
  To-Do_List/To-Do_ListTests/To_Do_ListTests.swift
  To-Do_List/To-Do_ListUITests/To_Do_ListUITests.swift
  To-Do_List/To-Do_ListUITests/To_Do_ListUITestsLaunchTests.swift
Labels: review-iOS

#16 [team35 bangtae & 난정] 1주차 수요일 PR
  .gitignore
  README.md
  babel.config.json
  dist/bundle.js
  dist/index.html
  index.html
  js/components/model/scheduleModel.js
  js/components/schedule/scheduleCard.js
  js/components/schedule/scheduleColumn.js
  js/components/schedule/scheduleRegisterCard.js
  js/index.js
  package-lock.json
  package.json
  style.css
  styles/_global.scss
  styles/_header.scss
  styles/_history.scss
  styles/_mixin.scss
  styles/_reset.scss
  styles/_schedule.scss
  styles/style.css
  styles/style.scss
  styles/user-img-sample.jpg
  webpack.config.js
Labels: review-FE

#21 [team-13][BE] To-do list 그룹 프로젝트 1주차(수) PR
  Client/iOS/TodoList.xcodeproj/project.pbxproj
  Client/iOS/TodoList.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  Client/iOS/TodoList.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  Client/iOS/TodoList.xcodeproj/project.xcworkspace/xcuserdata/jsj.xcuserdatad/UserInterfaceState.xcuserstate
  Client/iOS/TodoList.xcodeproj/project.xcworkspace/xcuserdata/sanghwiback.xcuserdatad/UserInterfaceState.xcuserstate
  Client/iOS/TodoList.xcodeproj/xcuserdata/jsj.xcuserdatad/xcschemes/xcschememanagement.plist
  Client/iOS/TodoList.xcodeproj/xcuserdata/sanghwiback.xcuserdatad/xcschemes/xcschememanagement.plist
  Client/iOS/TodoList/AppDelegate.swift
  Client/iOS/TodoList/Assets.xcassets/AccentColor.colorset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/AppIcon.appiconset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/Contents.json
  Client/iOS/TodoList/Base.lproj/LaunchScreen.storyboard
  Client/iOS/TodoList/Base.lproj/Main.storyboard
  Client/iOS/TodoList/Info.plist
  Client/iOS/TodoList/SceneDelegate.swift
  Client/iOS/TodoList/ViewController.swift
  Client/iOS/TodoListTests/Info.plist
  Client/iOS/TodoListTests/TodoListTests.swift
  Client/iOS/TodoListUITests/Info.plist
  Client/iOS/TodoListUITests/TodoListUITests.swift
  Server/.gitignore
  Server/build.gradle
  Server/gradle/wrapper/gradle-wrapper.jar
  Server/gradle/wrapper/gradle-wrapper.properties
  Server/gradlew
  Server/gradlew.bat
  Server/settings.gradle
  Server/src/main/java/com/todolist/TodolistApplication.java
  Server/src/main/java/com/todolist/controller/CardController.java
  Server/src/main/java/com/todolist/controller/HistoryController.java
  Server/src/main/java/com/todolist/domain/Card.java
  Server/src/main/java/com/todolist/domain/History.java
  Server/src/main/java/com/todolist/repository/CardRepository.java
  Server/src/main/java/com/todolist/repository/HistoryRepository.java
  Server/src/main/java/com/todolist/service/CardService.java
  Server/src/main/java/com/todolist/service/HistoryService.java
  Server/src/main/resources/application.yml
  Server/src/main/resources/data.sql
  Server/src/main/resources/schema.sql
  Server/src/test/java/com/todolist/TodolistApplicationTests.java
  Server/src/test/java/com/todolist/db/DBAccessTest.java
Labels: review-BE

#55 [Team-28] [FE] 1주차 첫번째 PR
  .gitignore
  README.md
  package-lock.json
  package.json
  src/app.js
  src/app.scss
  src/components/header/Header.js
  src/components/header/Header.scss
  src/components/header/menu/Menu.js
  src/components/header/menu/Menu.scss
  src/components/main/Main.js
  src/components/main/column-container/Column/Column.js
  src/components/main/column-container/Column/Column.scss
  src/components/main/column-container/Column/card/Card.js
  src/components/main/column-container/Column/card/Card.scss
  src/components/main/column-container/Column/card/alert/Alert.js
  src/components/main/column-container/Column/card/alert/Alert.scss
  src/components/main/column-container/ColumnContainer.js
  src/components/main/fab/Fab.js
  src/components/main/fab/Fab.scss
  src/images/close.png
  src/images/column-close.png
  src/images/column-plus.png
  src/images/menu.png
  src/images/plus.png
  src/index.html
  src/scss/_reset.scss
  src/scss/_variable.scss
  src/stores/columnStore.js
  src/stores/menuStore.js
  webpack.config.js
Labels: review-FE

#15 [team-8][BE] todo-list 1주차 #1
  be/.gitignore
  be/build.gradle
  be/gradle/wrapper/gradle-wrapper.jar
  be/gradle/wrapper/gradle-wrapper.properties
  be/gradlew
  be/gradlew.bat
  be/settings.gradle
  be/src/main/java/todolist/TodoListApplication.java
  be/src/main/java/todolist/controller/CardController.java
  be/src/main/java/todolist/domain/Card.java
  be/src/main/java/todolist/dto/CardDto.java
  be/src/main/java/todolist/dto/CardsDto.java
  be/src/main/java/todolist/repository/CardMemoryRepository.java
  be/src/main/java/todolist/repository/TodoRepository.java
  be/src/main/java/todolist/service/CardService.java
  be/src/main/resources/application.properties
  be/src/test/java/todolist/TodoListApplicationTests.java
  be/src/test/java/todolist/repository/CardMemoryRepositoryTest.java
  be/src/test/java/todolist/service/CardServiceTest.java
  iOS/TodoList/ViewController.swift
Labels: review-BE

#39 [FE] [team-31] 1주차 첫번 째 PR 요청드립니다.
  .eslintrc.json
  .gitignore
  .prettierrc
  babel.config.json
  dist/bundle.js
  package-lock.json
  package.json
  static/index.html
  static/resources/css/main.css
  static/resources/images/common/icon-add-blue.png
  static/resources/images/common/icon-add-gray.png
  static/resources/images/common/icon-add.png
  static/resources/images/common/icon-aside.png
  static/resources/images/common/icon-close-gray.png
  static/resources/images/common/icon-close-red.png
  static/resources/images/common/icon-close.png
  static/resources/images/fab.png
  static/resources/scss/components/_column.scss
  static/resources/scss/components/_header.scss
  static/resources/scss/components/_history.scss
  static/resources/scss/components/_layout.scss
  static/resources/scss/components/_popup.scss
  static/resources/scss/main.scss
  static/resources/scss/utils/_common.scss
  static/resources/scss/utils/_mixin.scss
  static/resources/scss/utils/_reset.scss
  static/resources/scss/utils/_variables.scss
  webpack.config.js
Labels: review-FE

#8 [team-14][iOS] 현재까지의 진행사항 PR
  .github/ISSUE_TEMPLATE/custom.md
  .gitignore
  README.md
  iOSProject/TodoList.xcodeproj/project.pbxproj
  iOSProject/TodoList.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOSProject/TodoList.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOSProject/TodoList.xcodeproj/xcuserdata/seonghashin.xcuserdatad/xcschemes/xcschememanagement.plist
  iOSProject/TodoList/Configuration/Info.plist
  iOSProject/TodoList/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  iOSProject/TodoList/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOSProject/TodoList/Resources/Assets.xcassets/Contents.json
  iOSProject/TodoList/Resources/Assets.xcassets/ic_add.imageset/Contents.json
  iOSProject/TodoList/Resources/Assets.xcassets/ic_add.imageset/ic_add.png
  iOSProject/TodoList/Resources/Assets.xcassets/ic_add.imageset/ic_add@2x.png
  iOSProject/TodoList/Resources/Assets.xcassets/ic_add.imageset/ic_add@3x.png
  iOSProject/TodoList/Resources/Assets.xcassets/ic_menu.imageset/Contents.json
  iOSProject/TodoList/Resources/Assets.xcassets/ic_menu.imageset/ic_menu.png
  iOSProject/TodoList/Resources/Assets.xcassets/ic_menu.imageset/ic_menu@2x.png
  iOSProject/TodoList/Resources/Assets.xcassets/ic_menu.imageset/ic_menu@3x.png
  iOSProject/TodoList/Sources/API/BaseTarget.swift
  iOSProject/TodoList/Sources/API/TodoTarget.swift
  iOSProject/TodoList/Sources/AppDelegate.swift
  iOSProject/TodoList/Sources/Common/PaddingLabel.swift
  iOSProject/TodoList/Sources/Common/PlaceholderTextView.swift
  iOSProject/TodoList/Sources/Extension/Date+Extension.swift
  iOSProject/TodoList/Sources/Extension/UIColor+Extension.swift
  iOSProject/TodoList/Sources/Extension/UIConrtol+Extension.swift
  iOSProject/TodoList/Sources/Extension/UITextFieldView+Extension.swift
  iOSProject/TodoList/Sources/Extension/UITextView+Extension.swift
  iOSProject/TodoList/Sources/Extension/UiViewController+Extension.swift
  iOSProject/TodoList/Sources/Model/Card.swift
  iOSProject/TodoList/Sources/Present/Log/LogViewController.swift
  iOSProject/TodoList/Sources/Present/Log/LogViewModel.swift
  iOSProject/TodoList/Sources/Present/Main/MainViewController.swift
  iOSProject/TodoList/Sources/Present/Main/View/MainTitleBarView.swift
  iOSProject/TodoList/Sources/Present/Todo/ColumnViewController.swift
  iOSProject/TodoList/Sources/Present/Todo/ColumnViewModel.swift
  iOSProject/TodoList/Sources/Present/Todo/View/ColumnViewCell.swift
  iOSProject/TodoList/Sources/Repository/Base/MockURLSession.swift
  iOSProject/TodoList/Sources/Repository/Base/SessionError.swift
  iOSProject/TodoList/Sources/Repository/Base/URLSessionProtocol.swift
  iOSProject/TodoList/Sources/Repository/Base/URLSessionProvider.swift
  iOSProject/TodoList/Sources/Repository/CardPopup/CardPopupViewController.swift
  iOSProject/TodoList/Sources/Repository/CardPopup/CardPopupViewModel.swift
  iOSProject/TodoList/Sources/Repository/NetworkRepository.swift
  iOSProject/TodoList/Sources/Repository/Todo/TodoRepository.swift
  iOSProject/TodoList/Sources/Repository/Todo/TodoRepositoryImpl.swift
  iOSProject/TodoList/Sources/SceneDelegate.swift
  iOS진행상황.md
Labels: review-iOS

#32 [team-19] Todo-list 1주차 #1 코드리뷰 요청
  .github/ISSUE_TEMPLATE/feature.md
  .gitignore
  README.md
  build/babel.config.json
  build/dist/bundle.js
  build/webpack.config.js
  client/public/index.html
  client/public/svg/icon-add.svg
  client/public/svg/icon-delete.svg
  client/public/svg/icon-menu.svg
  client/public/svg/profile.svg
  client/src/js/app.js
  client/src/js/constants/imagePath.js
  client/src/js/header/view.js
  client/src/js/main/view.js
  client/src/js/sidebar/view.js
  client/src/js/store/activationStore.js
  client/src/js/utils/utils.js
  client/src/style/css/style.css
  client/src/style/css/style.css.map
  client/src/style/scss/abstracts/_mixins.scss
  client/src/style/scss/abstracts/_variables.scss
  client/src/style/scss/base/_reset.scss
  client/src/style/scss/layout/header/_header.scss
  client/src/style/scss/layout/main/_column-list.scss
  client/src/style/scss/layout/main/_column-task-list.scss
  client/src/style/scss/layout/sidebar/_sidebar.scss
  client/src/style/scss/style.scss
  package-lock.json
  package.json
  server/data/db.json
  server/data/sidebar.js
Labels: review-FE

#11 [team-14][BE] To-do list 그룹 프로젝트 1주차(수) PR
  .gitignore
  README.md
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/example/backend/BackendApplication.java
  backend/src/main/java/com/example/backend/config/SwaggerConfig.java
  backend/src/main/java/com/example/backend/domain/Card.java
  backend/src/main/java/com/example/backend/domain/Column.java
  backend/src/main/java/com/example/backend/web/controller/CardsController.java
  backend/src/main/java/com/example/backend/web/dto/CardListResponseDto.java
  backend/src/main/java/com/example/backend/web/dto/CardSaveRequestDto.java
  backend/src/main/java/com/example/backend/web/dto/CardsMoveRequestDto.java
  backend/src/main/java/com/example/backend/web/dto/CardsUpdateRequestDto.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/sql/schema.sql
  backend/src/test/java/com/example/backend/BackendApplicationTests.java
Labels: review-BE

#41 [Team-03][ Android ] 데이터 클래스 정의 및 어뎁터 구현
  android/.gitignore
  android/app/.gitignore
  android/app/build.gradle
  android/app/proguard-rules.pro
  android/app/src/androidTest/java/com/example/todo/ExampleInstrumentedTest.kt
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/todo/common/ActionDiffCallback.kt
  android/app/src/main/java/com/example/todo/common/Common.kt
  android/app/src/main/java/com/example/todo/common/TodoDiffCallback.kt
  android/app/src/main/java/com/example/todo/common/timeDiffUtil.kt
  android/app/src/main/java/com/example/todo/model/ActionLog.kt
  android/app/src/main/java/com/example/todo/model/TodoItem.kt
  android/app/src/main/java/com/example/todo/ui/action/ActionAdapter.kt
  android/app/src/main/java/com/example/todo/ui/toDo/ToDoActivity.kt
  android/app/src/main/java/com/example/todo/ui/toDo/TodoAdapter.kt
  android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  android/app/src/main/res/drawable/ic_baseline_menu_24.xml
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/layout-sw720dp-land/activity_todo.xml
  android/app/src/main/res/layout/action_log_item.xml
  android/app/src/main/res/layout/activity_todo.xml
  android/app/src/main/res/layout/todo_item.xml
  android/app/src/main/res/menu/toolbar_action.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/values/themes.xml
  android/app/src/test/java/com/example/todo/ExampleUnitTest.kt
  android/build.gradle
  android/gradle.properties
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle
  backend/README.md
Labels: review-android

#113 [team35 - bangtae & nanjeong] 1주차 금요일 PR
  js/components/model/scheduleModel.js
  js/components/schedule/scheduleCard.js
  js/components/schedule/scheduleColumn.js
  js/components/schedule/scheduleDeleteConfirm.js
  js/components/schedule/scheduleEditCard.js
  js/components/schedule/scheduleRegisterCard.js
  js/index.js
  js/utils.js
  package-lock.json
  package.json
  styles/_global.scss
  styles/_schedule.scss
  styles/style.css
Labels: review-FE

#90 [team29][FE] 마크업, 스타일 진행중
  .eslintrc.json
  .prettierrc
  assets/icons/style.css
  assets/icons/todo.svg
  assets/icons/todo.ttf
  assets/icons/todo.woff
  component.html
  index.html
  package-lock.json
  package.json
  src/app.js
  src/store.js
  src/utils/utils.js
  styles/bootstrap-grid.min.css
  styles/bootstrap-grid.min.css.map
  styles/main.scss
  styles/scss/base/_hidden.scss
  styles/scss/base/_normalize.scss
  styles/scss/base/_reset.scss
  styles/scss/components/_header.scss
  styles/scss/components/_main.scss
  styles/scss/components/_todo-column.scss
  styles/scss/components/_todo-list.scss
  styles/scss/constants/_box-shadow.scss
  styles/scss/constants/_colors.scss
  styles/scss/constants/_z-index.scss
  styles/scss/mixins/_flexbox.scss
  styles/scss/mixins/_font.scss
  styles/scss/mixins/_pos-align.scss
  styles/scss/mixins/_scrollbar.scss
  styles/scss/modules/_badge.scss
  styles/scss/modules/_buttons.scss
  webpack.config.js
Labels: review-FE

#76 [team-14][BE] To-do list 그룹 프로젝트 1주차(금) PR
  backend/build.gradle
  backend/src/main/java/com/example/backend/domain/Card.java
  backend/src/main/java/com/example/backend/domain/repository/CardJdbcTemplateRepository.java
  backend/src/main/java/com/example/backend/domain/repository/CardRepository.java
  backend/src/main/java/com/example/backend/service/CardService.java
  backend/src/main/java/com/example/backend/web/controller/CardsController.java
  backend/src/main/java/com/example/backend/web/dto/CardListResponseDto.java
  backend/src/main/java/com/example/backend/web/dto/CardMoveRequestDto.java
  backend/src/main/java/com/example/backend/web/dto/CardSaveRequestDto.java
  backend/src/main/java/com/example/backend/web/dto/CardUpdateRequestDto.java
  backend/src/main/java/com/example/backend/web/dto/CardsMoveRequestDto.java
  backend/src/main/java/com/example/backend/web/dto/Column.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/main/resources/sql/schema.sql
Labels: review-BE

#70 [TEAM-02][BE] TodoList 카드 등록 기능
  backend/todolist/README.md
  backend/todolist/build.gradle
  backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDto.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
  backend/todolist/src/main/java/kr/codesquad/todolist/config/SwaggerConfig.java
Labels: review-BE

#81 [team-13][BE] To-do list 그룹 프로젝트 1주차(금) 2번째 PR
  Server/build.gradle
  Server/src/main/java/com/todolist/controller/CardController.java
  Server/src/main/java/com/todolist/domain/BoardType.java
  Server/src/main/java/com/todolist/domain/Card.java
  Server/src/main/java/com/todolist/domain/User.java
  Server/src/main/java/com/todolist/domain/dto/CardCreateDto.java
  Server/src/main/java/com/todolist/domain/dto/CardInformationDto.java
  Server/src/main/java/com/todolist/domain/dto/CardPatchDto.java
  Server/src/main/java/com/todolist/domain/dto/CardResponseDto.java
  Server/src/main/java/com/todolist/exception/ExceptionType.java
  Server/src/main/java/com/todolist/exception/GlobalException.java
  Server/src/main/java/com/todolist/exception/GlobalExceptionHandler.java
  Server/src/main/java/com/todolist/repository/CardRepository.java
  Server/src/main/java/com/todolist/repository/KeyHolderGenerator.java
  Server/src/main/java/com/todolist/service/CardService.java
  Server/src/main/resources/application.yml
  Server/src/main/resources/data.sql
  Server/src/main/resources/schema.sql
  Server/src/test/java/com/todolist/db/DBAccessTest.java
Labels: review-BE

#101 [Team-06][BE Shine & 땃쥐] 2022/04/06 2차 PR
  BE/README.md
  BE/src/main/java/codesquad/todo/domain/column/Column.java
  BE/src/main/java/codesquad/todo/domain/column/ColumnRepository.java
  BE/src/main/java/codesquad/todo/domain/column/MemoryColumnRepository.java
  BE/src/main/java/codesquad/todo/service/ColumnService.java
  BE/src/main/java/codesquad/todo/web/works/WorkController.java
  BE/src/main/java/codesquad/todo/web/works/dto/WorkMoveRequest.java
  BE/src/main/java/codesquad/todo/web/works/dto/WorkMoveResponse.java
Labels: review-BE

#118 [Team-05 BE nathan & 피오] 카드 생성 기능 구현(미완)
  backend/build.gradle
  backend/src/main/java/com/team05/todolist/controller/CardController.java
  backend/src/main/java/com/team05/todolist/domain/Card.java
  backend/src/main/java/com/team05/todolist/domain/Event.java
  backend/src/main/java/com/team05/todolist/domain/Log.java
  backend/src/main/java/com/team05/todolist/domain/Section.java
  backend/src/main/java/com/team05/todolist/domain/dto/CardDTO.java
  backend/src/main/java/com/team05/todolist/domain/dto/LogDTO.java
  backend/src/main/java/com/team05/todolist/domain/dto/ResponseDTO.java
  backend/src/main/java/com/team05/todolist/repository/CardRepository.java
  backend/src/main/java/com/team05/todolist/repository/JdbcCardRepository.java
  backend/src/main/java/com/team05/todolist/repository/JdbcLogRepository.java
  backend/src/main/java/com/team05/todolist/repository/LogRepository.java
  backend/src/main/java/com/team05/todolist/service/CardService.java
  backend/src/main/resources/application.properties
Labels: review-BE

#104 [Team-10][BE] Todo-list 1주차 PR #2
  BE/.gitignore
  BE/src/main/java/kr/codesquad/todolist/controller/mockupController.java
  BE/src/main/java/kr/codesquad/todolist/domain/Card.java
  BE/src/main/java/kr/codesquad/todolist/dto/CardDto.java
  BE/src/main/java/kr/codesquad/todolist/dto/CardResponse.java
  BE/src/main/java/kr/codesquad/todolist/repository/JdbcCardRepository.java
  BE/src/main/java/kr/codesquad/todolist/service/CardService.java
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/kr/codesquad/todolist/repository/JdbcCardRepositoryTest.java
Labels: review-BE

#71 [Team 17][FE] Todo List 1주차 PR2
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/img/close.png
  frontend/src/img/user.svg
  frontend/src/scss/reset.scss
  frontend/src/scss/style.scss
  frontend/webpack.config.js
Labels: review-FE

#20 [team-18][FE] Readme 작성 & 빌드 설정
  .eslintrc.json
  .gitignore
  .prettierignore
  .vscode/settings.json
  README.md
  babel.config.json
  data.json
  package-lock.json
  package.json
  prettierrc.json
  src/app.html
  src/app.js
  src/components/Column.js
  src/components/Header.js
  src/core/Component.js
  src/style/images/delete.png
  src/style/images/menuButton.png
  src/style/images/plus.png
  src/style/scss/Column.scss
  src/style/scss/Header.scss
  src/style/scss/style.scss
  webpack.config.js
Labels: review-FE

#102 [Team-21] 1주차 2번째 PR - Khan + Nick
  FE/README.md
  FE/public/index.html
  FE/src/JS/drag-drop/drag-drop.js
  FE/src/JS/mok-data/data.js
  FE/src/JS/mok-data/mokData.json
  FE/src/JS/mok-data/sidebar-mokData.json
  FE/src/JS/todo/app.js
  FE/src/JS/todo/controller.js
  FE/src/JS/todo/model.js
  FE/src/JS/todo/view-template.js
  FE/src/JS/todo/view.js
  FE/src/JS/utility/fetchRequest.js
  FE/src/style/header/header.css
  FE/src/style/header/menu-icon.css
  FE/src/style/header/side-bar/sidebar-card.css
  FE/src/style/header/side-bar/sidebar.css
  FE/src/style/header/sidebar.css
  FE/src/style/main/card.css
  FE/src/style/main/column.css
  FE/src/style/reset/reset.css
Labels: review-FE

#119 [iOS] team-06 1주차 2번째 PR요청입니다!
  TodoList/TodoList.xcodeproj/project.pbxproj
  TodoList/TodoList/AppDelegate.swift
  TodoList/TodoList/Base.lproj/LaunchScreen.storyboard
  TodoList/TodoList/Base.lproj/Main.storyboard
  TodoList/TodoList/CardBoardViewController.swift
  TodoList/TodoList/SceneDelegate.swift
  TodoList/TodoList/TodoStoryboard.storyboard
  TodoList/TodoList/TodoViewController.swift
  TodoList/TodoList/domain/Card.swift
  TodoList/TodoList/domain/CardBoard.swift
  TodoList/TodoList/domain/CardFactory.swift
  TodoList/TodoList/domain/CardStatus.swift
  TodoList/TodoList/domain/CardUsable.swift
  TodoList/TodoList/view/CardBoardViewController.swift
  TodoList/TodoList/view/CardTableViewCell.swift
  TodoList/TodoList/view/CardTableViewController.swift
  TodoList/TodoList/view/delegate/CardTableDelegate.swift
  TodoList/TodoList/view/delegate/DoingCardDelegate.swift
  TodoList/TodoList/view/delegate/DoneCardDelegate.swift
  TodoList/TodoListTests/TodoListTests.swift
  TodoList/TodoListUITests/TodoListUITests.swift
  TodoList/TodoListUITests/TodoListUITestsLaunchTests.swift
Labels: review-iOS

#106 [Team-32][FE] 2차 PR - Muffin & Jinnie
  .gitignore
  README.md
  app.js
  babel.config.json
  components/Todo.js
  components/TodoColumn.js
  components/TodoEdit.js
  components/TodoEditTemplate.js
  components/TodoInput.js
  components/TodoNotice.js
  components/TodoNoticeAnimation.js
  constants/constants.js
  dist/bundle.js
  index.css
  index.html
  mocks/todos.js
  mocks/users.js
  package.json
  style/_alarm.scss
  style/_input.scss
  style/_mixins.scss
  style/_modal.scss
  style/_reset.scss
  style/_utilities.scss
  style/index.scss
  utils/localStorage.js
  webpack.config.js
Labels: review-FE

#96 [team-17][BE] Swagger 도입, Card API 구현 중
  backend/build.gradle
  backend/diagram.drawio
  backend/docker/local-database.yml
  backend/src/main/java/com/codesquad/todolist/TodolistApplication.java
  backend/src/main/java/com/codesquad/todolist/card/Card.java
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardCreateRequest.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardUpdateRequest.java
  backend/src/main/java/com/codesquad/todolist/column/Column.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnRepository.java
  backend/src/main/java/com/codesquad/todolist/config/SwaggerConfig.java
  backend/src/main/java/com/codesquad/todolist/user/User.java
  backend/src/main/java/com/codesquad/todolist/user/UserRepository.java
  backend/src/main/java/com/codesquad/todolist/util/GeneratedKeyHolderFactory.java
  backend/src/main/java/com/codesquad/todolist/util/KeyHolderFactory.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/codesquad/todolist/TodolistApplicationTests.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardSetUp.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
Labels: review-BE

#93 [team_31][BE YAN-K] 1주차 금요일PR
  todo-list/src/main/java/com/todolist/project/domain/CardStatus.java
  todo-list/src/main/java/com/todolist/project/domain/Status.java
  todo-list/src/main/java/com/todolist/project/domain/card/Card.java
  todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
  todo-list/src/main/java/com/todolist/project/service/CardService.java
  todo-list/src/main/java/com/todolist/project/web/CardController.java
  todo-list/src/main/java/com/todolist/project/web/dto/CardAddDto.java
  todo-list/src/main/java/com/todolist/project/web/dto/CardUpdateDto.java
  todo-list/src/main/java/com/todolist/project/web/dto/addCardDto.java
  todo-list/src/main/resources/application.properties
  todo-list/src/main/resources/data.sql
  todo-list/src/main/resources/schema.sql
Labels: review-BE

#82 [Team26 - BE] 히스토리 API 구현 및 카드 API 구현 중
  BE/build.gradle
  BE/src/main/java/com/team26/todolist/controller/CardController.java
  BE/src/main/java/com/team26/todolist/controller/HistoryController.java
  BE/src/main/java/com/team26/todolist/domain/Card.java
  BE/src/main/java/com/team26/todolist/domain/CardAction.java
  BE/src/main/java/com/team26/todolist/domain/CardStatus.java
  BE/src/main/java/com/team26/todolist/domain/History.java
  BE/src/main/java/com/team26/todolist/dto/request/CardDeleteRequest.java
  BE/src/main/java/com/team26/todolist/dto/request/CardMoveRequest.java
  BE/src/main/java/com/team26/todolist/dto/request/CardRegistrationRequest.java
  BE/src/main/java/com/team26/todolist/dto/request/CardUpdateRequest.java
  BE/src/main/java/com/team26/todolist/dto/response/CardResponse.java
  BE/src/main/java/com/team26/todolist/dto/response/HistoryResponse.java
  BE/src/main/java/com/team26/todolist/exception/EmptyCardStatusException.java
  BE/src/main/java/com/team26/todolist/repository/CardRepository.java
  BE/src/main/java/com/team26/todolist/repository/HistoryRepository.java
  BE/src/main/java/com/team26/todolist/repository/HistoryRepositoryImpl.java
  BE/src/main/java/com/team26/todolist/service/CardService.java
  BE/src/main/java/com/team26/todolist/service/CardServiceJdbc.java
  BE/src/main/java/com/team26/todolist/service/CardServiceMock.java
  BE/src/main/java/com/team26/todolist/service/HistoryService.java
  BE/src/main/java/com/team26/todolist/service/HistoryServiceImpl.java
  BE/src/main/resources/application-test.properties
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/sql/data.sql
  BE/src/main/resources/sql/schema.sql
  BE/src/test/java/com/team26/todolist/repository/HistoryRepositoryImplTest.java
  README.md
Labels: review-BE

#109 [Team-21 BE Ikjo & Hanse] Todo-List 프로젝트 1주차(금요일) 코드 리뷰 요청
  BE/build.gradle
  BE/src/main/java/com/todolist/controller/MainController.java
  BE/src/main/java/com/todolist/controller/WorkController.java
  BE/src/main/java/com/todolist/domain/Category.java
  BE/src/main/java/com/todolist/domain/Work.java
  BE/src/main/java/com/todolist/domain/WorkLog.java
  BE/src/main/java/com/todolist/dto/ColumnListDto.java
  BE/src/main/java/com/todolist/dto/WorkDto.java
  BE/src/main/java/com/todolist/dto/WorkListDto.java
  BE/src/main/java/com/todolist/dto/WorkLogDto.java
  BE/src/main/java/com/todolist/dto/WorkLogListDto.java
  BE/src/main/java/com/todolist/dto/WorkRequestFormDto.java
  BE/src/main/java/com/todolist/repository/CategoryRepository.java
  BE/src/main/java/com/todolist/repository/WorkLogRepository.java
  BE/src/main/java/com/todolist/repository/WorkRepository.java
  BE/src/main/java/com/todolist/service/WorkLogService.java
  BE/src/main/java/com/todolist/service/WorkService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: review-BE

#111 [Team-25] [FE] TODO LIST 1주차 두번째 PR
  .prettierrc
  db.json
  index.html
  nodemon.json
  package.json
  server.js
  src/client/js/api/actionApi.js
  src/client/js/api/index.js
  src/client/js/app.js
  src/client/js/components/ActionLayer.js
  src/client/js/components/Card.js
  src/client/js/components/Column.js
  src/client/js/components/Header.js
  src/client/js/core/Component.js
  src/client/js/store/ActionStore.js
  src/client/js/store/store.js
  src/client/js/utils/index.js
  src/client/style/_extends.scss
  src/client/style/_mixin.scss
  src/client/style/_reset.scss
  src/client/style/_variables.scss
  src/client/style/style.scss
  src/js/app.js
  src/server/init.js
  src/server/middleware.js
  src/style/style.scss
  webpack.config.cjs
Labels: review-FE

#126 [Team-02][BE] 1주 - 3차 PR
  backend/todolist/README.md
  backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDto.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
  backend/todolist/src/test/java/kr/codesquad/todolist/card/CardServiceTest.java
Labels: review-BE

#67 [team-01][BE] API - Todo를 특정 id로 조회 요청
  BE/.gitignore
  BE/build.gradle
  BE/src/main/java/codesquad/be/todoserver/TodoserverApplication.java
  BE/src/main/java/codesquad/be/todoserver/controller/TodoController.java
  BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
  BE/src/main/java/codesquad/be/todoserver/exception/NoSuchTodoFoundException.java
  BE/src/main/java/codesquad/be/todoserver/repository/TodoJdbcRepository.java
  BE/src/main/java/codesquad/be/todoserver/repository/TodoRepository.java
  BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
  BE/src/test/java/codesquad/be/todoserver/TodosApiAcceptanceTest.java
  BE/src/test/java/codesquad/be/todoserver/TodoserverApplicationTests.java
  BE/src/test/java/codesquad/be/todoserver/controller/TodoControllerTest.java
  BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
  BE/src/test/java/codesquad/be/todoserver/service/TodoServiceTest.java
Labels: review-BE

#98 [Team-05][Android] UI 리사이클러 뷰 및 다이얼로그 구현
  android/app/build.gradle
  android/app/src/main/java/com/codesquad/aos/todolist/common/utils/VerticalItemDecorator.kt
  android/app/src/main/java/com/codesquad/aos/todolist/data/model/Card.kt
  android/app/src/main/java/com/codesquad/aos/todolist/data/model/Log.kt
  android/app/src/main/java/com/codesquad/aos/todolist/ui/MainActivity.kt
  android/app/src/main/java/com/codesquad/aos/todolist/ui/TodoViewModel.kt
  android/app/src/main/java/com/codesquad/aos/todolist/ui/adapter/LogCardListAdapter.kt
  android/app/src/main/java/com/codesquad/aos/todolist/ui/adapter/TodoCardListAdapter.kt
  android/app/src/main/java/com/codesquad/aos/todolist/ui/adapter/TodoCardPagingAdapter.kt
  android/app/src/main/java/com/codesquad/aos/todolist/ui/dialog/CompleteDialogFragment.kt
  android/app/src/main/java/com/codesquad/aos/todolist/ui/dialog/ProgressDialogFragment.kt
  android/app/src/main/java/com/codesquad/aos/todolist/ui/dialog/TodoDialogFragment.kt
  android/app/src/main/res/drawable/button_background.xml
  android/app/src/main/res/drawable/user_img.png
  android/app/src/main/res/layout-sw600dp-land/activity_main.xml
  android/app/src/main/res/layout-sw600dp-land/item_log.xml
  android/app/src/main/res/layout-sw600dp-land/item_todo_card.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_card_dialog.xml
  android/app/src/main/res/layout/item_log.xml
  android/app/src/main/res/layout/item_todo_card.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/text_style.xml
  android/app/src/main/res/values/themes.xml
  backend/build.gradle
  backend/src/main/resources/application.properties
Labels: review-android

#115 [Team-07][iOS] Inspector / PopUp View 구현
  ios/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  ios/ToDoListApp/ToDoListApp.xcodeproj/xcshareddata/xcschemes/ToDoListApp.xcscheme
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/addButton.imageset/Contents.json
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/addButton.imageset/addButton.png
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/addButton.imageset/addButton@2x.png
  ios/ToDoListApp/ToDoListApp/Assets.xcassets/addButton.imageset/addButton@3x.png
  ios/ToDoListApp/ToDoListApp/Base.lproj/Main.storyboard
  ios/ToDoListApp/ToDoListApp/Constant/Constant.swift
  ios/ToDoListApp/ToDoListApp/Controller/ContainerViewController.swift
  ios/ToDoListApp/ToDoListApp/Controller/DoneViewController.swift
  ios/ToDoListApp/ToDoListApp/Controller/InProgressViewController.swift
  ios/ToDoListApp/ToDoListApp/Controller/InspectorViewController.swift
  ios/ToDoListApp/ToDoListApp/Controller/KanbanColumnViewController.swift
  ios/ToDoListApp/ToDoListApp/Controller/MainViewController.swift
  ios/ToDoListApp/ToDoListApp/Extension/CALayer+addBorder.swift
  ios/ToDoListApp/ToDoListApp/Model/CellData.swift
  ios/ToDoListApp/ToDoListApp/Model/Delegate & DataSource/InspectorTableViewDataSource.swift
  ios/ToDoListApp/ToDoListApp/Model/Delegate & DataSource/KanbanTableViewDataSource.swift
  ios/ToDoListApp/ToDoListApp/Model/Delegate & DataSource/MainViewControllerDelegate.swift
  ios/ToDoListApp/ToDoListApp/Model/InspectorTableCellData.swift
  ios/ToDoListApp/ToDoListApp/Model/KanbanTableCellData.swift
  ios/ToDoListApp/ToDoListApp/Model/KanbanType.swift
  ios/ToDoListApp/ToDoListApp/View/InspectorTableViewCell.swift
  ios/ToDoListApp/ToDoListApp/View/KanbanTableViewCell.swift
  ios/ToDoListApp/ToDoListApp/View/PopUpView.swift
  ios/ToDoListApp/ToDoListApp/View/TableTitleView.swift
  ios/ToDoListApp/ToDoListApp/View/TitleView.swift
Labels: review-iOS

#80 [Team-11] Eddy & Jason / 1주차 / Networking을 위한 Task와 Log 모델 Decoding UnitTest 구현
  iOS/todo-list/todo-list.xcodeproj/project.pbxproj
  iOS/todo-list/todo-list/Model/Action.swift
  iOS/todo-list/todo-list/Model/Log.swift
  iOS/todo-list/todo-list/Model/NetworkManager.swift
  iOS/todo-list/todo-list/Model/Task.swift
  iOS/todo-list/todo-list/Resource/Base.lproj/Main.storyboard
  iOS/todo-list/todo-list/Resource/dummyLogResponse.json
  iOS/todo-list/todo-list/Resource/dummyTaskResponse.json
  iOS/todo-list/todo-list/View/LogTableViewCell.swift
  iOS/todo-list/todo-list/ViewController/ActivityRecoderController.swift
  iOS/todo-list/todo-listTests/todo_listTests.swift
Labels: review-iOS

#91 [team-10][iOS] 1주차-2 : 카드리스트 제작과 메인 뷰에 .xib로 만든 뷰 연결 및 카드 모델 대략적으로 구현
  ToDoList/ToDoList.xcodeproj/project.pbxproj
  ToDoList/ToDoList/Base.lproj/Main.storyboard
  ToDoList/ToDoList/CardListTableViewCell.xib
  ToDoList/ToDoList/CardListTableViewHeaderView.swift
  ToDoList/ToDoList/CardListTableViewHeaderView.xib
  ToDoList/ToDoList/Controller/CardListViewController.swift
  ToDoList/ToDoList/Controller/MainViewController.swift
  ToDoList/ToDoList/Model/Caption.swift
  ToDoList/ToDoList/Model/Card.swift
  ToDoList/ToDoList/Model/CardFactory.swift
  ToDoList/ToDoList/Model/CardManager.swift
  ToDoList/ToDoList/Model/ID.swift
  ToDoList/ToDoList/View/Base.lproj/Main.storyboard
  ToDoList/ToDoList/View/CardListTableViewCell.swift
  ToDoList/ToDoList/View/CardListTableViewCell.xib
  ToDoList/ToDoList/View/CardListView.xib
  ToDoList/ToDoList/ViewController.swift
Labels: review-iOS

#79 [Team-11 BE: Hoo & Riako] TODO-LIST Card, ActivityLog MVC 패턴 구조 개선
  backend/build.gradle
  backend/src/main/java/com/hooria/todo/config/WebMvcConfig.java
  backend/src/main/java/com/hooria/todo/controller/ActivityLogController.java
  backend/src/main/java/com/hooria/todo/controller/CardController.java
  backend/src/main/java/com/hooria/todo/controller/MemberController.java
  backend/src/main/java/com/hooria/todo/domain/ActivityLog.java
  backend/src/main/java/com/hooria/todo/domain/Card.java
  backend/src/main/java/com/hooria/todo/domain/Device.java
  backend/src/main/java/com/hooria/todo/domain/Member.java
  backend/src/main/java/com/hooria/todo/domain/Status.java
  backend/src/main/java/com/hooria/todo/dto/ActivityLogsResponse.java
  backend/src/main/java/com/hooria/todo/interceptor/EncodingInterceptor.java
  backend/src/main/java/com/hooria/todo/repository/ActivityLogRepository.java
  backend/src/main/java/com/hooria/todo/repository/CardRepository.java
  backend/src/main/java/com/hooria/todo/service/ActivityLogService.java
  backend/src/main/java/com/hooria/todo/service/MemberService.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/hooria/todo/controller/ActivityLogControllerMockTest.java
  backend/src/test/java/com/hooria/todo/controller/MemberControllerMockTest.java
  backend/src/test/java/com/hooria/todo/repository/ActivityLogRepositoryTest.java
  backend/src/test/java/com/hooria/todo/repository/CardRepositoryTest.java
  backend/src/test/java/com/hooria/todo/repository/MemberRepositoryTest.java
  backend/src/test/resources/data.sql
  backend/src/test/resources/schema.sql
Labels: review-BE

#89 [Team-28] [FE] CRUD 기능 구현 & mongoose를 활용한 express 서버
  babel.config.js
  package-lock.json
  package.json
  server/.gitignore
  server/models/card.js
  server/models/column.js
  server/package-lock.json
  server/package.json
  server/routes/columns.js
  server/server.js
  src/app.js
  src/components/header/Header.js
  src/components/header/Header.scss
  src/components/header/menu/Menu.js
  src/components/header/menu/Menu.scss
  src/components/main/Main.js
  src/components/main/column-container/Column/Column.js
  src/components/main/column-container/Column/Column.scss
  src/components/main/column-container/Column/card/Card.js
  src/components/main/column-container/Column/card/Card.scss
  src/components/main/column-container/ColumnContainer.js
  src/components/main/fab/Fab.js
  src/images/close-activated.png
  src/images/column-close-activated.png
  src/images/column-plus-activated.png
  src/index.html
  src/scss/_reset.scss
  src/scss/_variable.scss
  src/stores/columnStore.js
  webpack.config.js
Labels: review-FE

#97 [Team26 - FE] Todo-List 1주차
  FE/.eslintrc.js
  FE/.gitignore
  FE/babel.config.json
  FE/package-lock.json
  FE/package.json
  FE/src/assets/menu.svg
  FE/src/assets/task-remove-default.svg
  FE/src/assets/task-remove-delete.svg
  FE/src/assets/worklist-add-default.svg
  FE/src/assets/worklist-add-hover.svg
  FE/src/assets/worklist-remove-default.svg
  FE/src/assets/worklist-remove-hover.svg
  FE/src/html/index.html
  FE/src/js/app.js
  FE/src/scss/_backgrounds.scss
  FE/src/scss/_colors.scss
  FE/src/scss/_header.scss
  FE/src/scss/_history.scss
  FE/src/scss/_modal.scss
  FE/src/scss/_reset.scss
  FE/src/scss/_task.scss
  FE/src/scss/_typography.scss
  FE/src/scss/_utils.scss
  FE/src/scss/_work.scss
  FE/src/scss/main.scss
  FE/webpack.config.js
Labels: review-FE

#112 [team-19] Todo-list 1주차 두번째 코드리뷰 요청
  client/public/index.html
  client/src/js/app.js
  client/src/js/header/view.js
  client/src/js/main/index.js
  client/src/js/main/list.js
  client/src/js/main/task.js
  client/src/js/main/taskDragHandler.js
  client/src/js/main/view.js
  client/src/js/sidebar/view.js
  client/src/js/store/todoListStore.js
  client/src/js/store/todolistStore.js
  client/src/js/utils/utils.js
  client/src/style/css/style.css
  client/src/style/css/style.css.map
  client/src/style/scss/abstracts/_variables.scss
  client/src/style/scss/layout/main/_column-list.scss
  client/src/style/scss/layout/main/_column-task-list.scss
  package.json
  server/data/db.json
Labels: review-FE

#83 [team_33] 1주차 금요일PR
  client/src/assets/emoji/user-img.png
  client/src/assets/fonts/icomoon.eot
  client/src/assets/fonts/icomoon.svg
  client/src/assets/fonts/icomoon.ttf
  client/src/assets/fonts/icomoon.woff
  client/src/index.html
  client/src/js/app.js
  client/src/js/main.js
  client/src/js/template.js
  client/src/js/todos.js
  client/src/js/util.js
  client/src/styles/_common.scss
  client/src/styles/_icons.scss
  client/src/styles/_reset.scss
  client/src/styles/body/_body.scss
  client/src/styles/css/main.css
  client/src/styles/css/main.css.map
  client/src/styles/css/reset.css
  client/src/styles/header/_headerBar.scss
  client/src/styles/main.scss
  package-lock.json
  package.json
  server/db.json
  webpack.config.js
Labels: review-FE

#92 [team-16][iOS] 1주차 - 2 : 헤더뷰, 메모 캔버스 뷰 구현
  todo-list-ios/TODOList/TODOList.xcodeproj/project.pbxproj
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Color/Black.colorset/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Color/Blue.colorset/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Color/Gray4.colorset/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Color/Gray5.colorset/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Color/Gray6.colorset/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Color/LightBlue.colorset/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Color/Red.colorset/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Color/White.colorset/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Icons/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Icons/add.imageset/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Icons/add.imageset/Vector.png
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Icons/close.imageset/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Icons/close.imageset/Vector.png
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Icons/emoji.imageset/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Icons/emoji.imageset/user img.png
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Icons/menu.imageset/Contents.json
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/Icons/menu.imageset/Vector.png
  todo-list-ios/TODOList/TODOList/Application/Assets.xcassets/emoji.imageset/congratu.jpeg
  todo-list-ios/TODOList/TODOList/Controllers/MainViewController.swift
  todo-list-ios/TODOList/TODOList/Controllers/MemoCanvasViewController.swift
  todo-list-ios/TODOList/TODOList/Delegates/HeaderViewDelegate.swift
  todo-list-ios/TODOList/TODOList/Delegates/SideViewDelegate.swift
  todo-list-ios/TODOList/TODOList/Models/History/HistoryInfo.swift
  todo-list-ios/TODOList/TODOList/Models/Memo/Memo.swift
  todo-list-ios/TODOList/TODOList/Resources/ResourceFactory.swift
  todo-list-ios/TODOList/TODOList/Views/HeaderView.swift
  todo-list-ios/TODOList/TODOList/Views/History/SideView.swift
  todo-list-ios/TODOList/TODOList/Views/History/SideViewTableViewCell.swift
  todo-list-ios/TODOList/TODOList/Views/HistoryStackView.swift
  todo-list-ios/TODOList/TODOList/Views/Memo/MemoCanvasView.swift
  todo-list-ios/TODOList/TODOList/Views/Memo/MemoContainerView.swift
  todo-list-ios/TODOList/TODOList/Views/Memo/MemoTableViewCell.swift
  todo-list-ios/TODOList/TODOList/Views/Memo/PopupCardView.swift
  todo-list-ios/TODOList/TODOList/Views/MemoCanvasView.swift
  todo-list-ios/TODOList/TODOList/Views/SideView.swift
  todo-list-ios/TODOList/TODOList/Views/Xib/PopupCardView.xib
Labels: review-iOS

#117 [FE] [team-31] 1주차 2번 째 PR 요청드립니다.
  .gitignore
  dist/bundle.js
  front/.eslintrc.json
  front/.prettierrc
  front/babel.config.json
  front/package-lock.json
  front/package.json
  front/static/index.html
  front/static/resources/css/main.css
  front/static/resources/css/main.css.map
  front/static/resources/images/common/icon-add-blue.png
  front/static/resources/images/common/icon-add-gray.png
  front/static/resources/images/common/icon-add.png
  front/static/resources/images/common/icon-aside.png
  front/static/resources/images/common/icon-close-gray.png
  front/static/resources/images/common/icon-close-red.png
  front/static/resources/images/common/icon-close.png
  front/static/resources/images/fab.png
  front/static/resources/js/app.js
  front/static/resources/scss/components/_column.scss
  front/static/resources/scss/components/_header.scss
  front/static/resources/scss/components/_history.scss
  front/static/resources/scss/components/_layout.scss
  front/static/resources/scss/components/_popup.scss
  front/static/resources/scss/main.scss
  front/static/resources/scss/utils/_common.scss
  front/static/resources/scss/utils/_mixin.scss
  front/static/resources/scss/utils/_reset.scss
  front/static/resources/scss/utils/variables/_color.scss
  front/static/resources/scss/utils/variables/_font.scss
  front/static/resources/scss/utils/variables/_size.scss
  front/webpack.config.js
  static/resources/scss/utils/_common.scss
  static/resources/scss/utils/_variables.scss
  webpack.config.js
Labels: review-FE

#95 [Team-03][Android] MVVM + retrofit 통신
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/todo/common/Common.kt
  android/app/src/main/java/com/example/todo/common/timeDiffUtil.kt
  android/app/src/main/java/com/example/todo/model/ActionLog.kt
  android/app/src/main/java/com/example/todo/network/ActionLogResponse.kt
  android/app/src/main/java/com/example/todo/network/JsonTodo.kt
  android/app/src/main/java/com/example/todo/network/RetrofitClient.kt
  android/app/src/main/java/com/example/todo/respository/ActionLogDataSource.kt
  android/app/src/main/java/com/example/todo/respository/ActionLogRemoteDataSource.kt
  android/app/src/main/java/com/example/todo/respository/ActionLogRepository.kt
  android/app/src/main/java/com/example/todo/respository/ToDoDataSource.kt
  android/app/src/main/java/com/example/todo/respository/ToDoRepository.kt
  android/app/src/main/java/com/example/todo/ui/action/ActionAdapter.kt
  android/app/src/main/java/com/example/todo/ui/common/actionLogBindingAdapter.kt
  android/app/src/main/java/com/example/todo/ui/toDo/ToDoActivity.kt
  android/app/src/main/java/com/example/todo/ui/toDo/ToDoViewModel.kt
  android/app/src/main/java/com/example/todo/ui/toDo/TodoAdapter.kt
  android/app/src/main/java/com/example/todo/ui/toDo/ViewModelFactory.kt
  android/app/src/main/res/layout-sw720dp-land/activity_todo.xml
  android/app/src/main/res/layout/action_log_item.xml
  android/app/src/main/res/layout/activity_todo.xml
  android/app/src/main/res/layout/todo_item.xml
Labels: review-android

#99 [Team 34] [Front] Millie & Hoi
  .prettierrc
  package-lock.json
  package.json
  server/db.json
  src/index.html
  src/js/constants/constant.js
  src/js/controller.js
  src/js/index.js
  src/js/store/store.js
  src/js/utils/util.js
  src/js/views/cardView.js
  src/js/views/columnsView.js
  src/js/views/header.js
  src/js/views/headerView.js
  src/js/views/main.js
  src/js/views/mainView.js
  src/js/views/newCardView.js
  src/scss/components/_card.scss
  src/scss/views/_todo.scss
  webpack.config.js
Labels: review-FE

#75 [team-07][BE][Jerry & 선을로] 메모리기반으로 기능구현 완료
  be/README.md
  be/todolist/src/main/java/team07/todolist/controller/CardController.java
  be/todolist/src/main/java/team07/todolist/domain/ActivityLog.java
  be/todolist/src/main/java/team07/todolist/domain/Card.java
  be/todolist/src/main/java/team07/todolist/repository/ActivityLogRepository.java
  be/todolist/src/main/java/team07/todolist/repository/CardRepository.java
  be/todolist/src/main/java/team07/todolist/repository/MemoryActivityLogRepository.java
  be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
  be/todolist/src/main/java/team07/todolist/service/ActivityLogService.java
  be/todolist/src/main/java/team07/todolist/service/CardService.java
Labels: review-BE

#125 [team-03][BackEnd] todo-list 1주차 2번째 PR
  backend/todo-app/.gitignore
  backend/todo-app/build.gradle
  backend/todo-app/gradlew
  backend/todo-app/gradlew.bat
  backend/todo-app/src/main/java/team03/todoapp/Service/CardService.java
  backend/todo-app/src/main/java/team03/todoapp/controller/CardController.java
  backend/todo-app/src/main/java/team03/todoapp/controller/CardsResponse.java
  backend/todo-app/src/main/java/team03/todoapp/controller/MockController.java
  backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardAddFormRequest.java
  backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardResponse.java
  backend/todo-app/src/main/java/team03/todoapp/controller/dto/CardsResponse.java
  backend/todo-app/src/main/java/team03/todoapp/controller/dto/HistoriesResponse.java
  backend/todo-app/src/main/java/team03/todoapp/controller/dto/HistoryResponse.java
  backend/todo-app/src/main/java/team03/todoapp/domain/Card.java
  backend/todo-app/src/main/java/team03/todoapp/domain/History.java
  backend/todo-app/src/main/java/team03/todoapp/repository/CardRepository.java
  backend/todo-app/src/main/resources/application.properties
  backend/todo-app/src/test/java/team03/todoapp/repository/CardRepositoryTest.java
Labels: review-BE

#84 [iJAVA] ToDoApp UI 구현
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  ios/.gitignore
  ios/README.md
  ios/TodoApp/TodoApp.xcodeproj/project.pbxproj
  ios/TodoApp/TodoApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/TodoApp/TodoApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  ios/TodoApp/TodoApp/AppDelegate.swift
  ios/TodoApp/TodoApp/Controllers/ActivityListViewController.storyboard
  ios/TodoApp/TodoApp/Controllers/ActivityListViewController.swift
  ios/TodoApp/TodoApp/Controllers/TodoListContainerViewController.swift
  ios/TodoApp/TodoApp/Controllers/TodoListViewController.storyboard
  ios/TodoApp/TodoApp/Controllers/TodoListViewController.swift
  ios/TodoApp/TodoApp/Extensions/Logger+Extensions.swift
  ios/TodoApp/TodoApp/Models/.gitkeep
  ios/TodoApp/TodoApp/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  ios/TodoApp/TodoApp/Resources/Assets.xcassets/AppIcon.appiconset/Contents.json
  ios/TodoApp/TodoApp/Resources/Assets.xcassets/Background.colorset/Contents.json
  ios/TodoApp/TodoApp/Resources/Assets.xcassets/Contents.json
  ios/TodoApp/TodoApp/SceneDelegate.swift
  ios/TodoApp/TodoApp/Supporting Files/Base.lproj/LaunchScreen.storyboard
  ios/TodoApp/TodoApp/Supporting Files/Base.lproj/Main.storyboard
  ios/TodoApp/TodoApp/Supporting Files/Info.plist
  ios/TodoApp/TodoApp/Views/.gitkeep
  ios/TodoApp/TodoApp/Views/ActivityCell.swift
  ios/TodoApp/TodoApp/Views/ToDoCell.swift
  ios/images/TodoApp-demo-1.gif
Labels: review-iOS

#128 [TEAM-02][BE] 2주차 1PR - 전체 목록 조회, 글쓰기 수정/삭제
  backend/todolist/README.md
  backend/todolist/src/main/java/kr/codesquad/todolist/card/Card.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardApiController.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardByStatus.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDao.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardDto.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardStatusNumber.java
  backend/todolist/src/main/java/kr/codesquad/todolist/config/SwaggerConfig.java
  backend/todolist/src/test/java/kr/codesquad/todolist/card/CardServiceTest.java
Labels: review-BE

#124 [team15][BE]민지노&테리 - 1주차 2차 PR
  backend/.gitignore
  backend/README.md
  backend/build.gradle
  backend/plan/AWS인스턴스구성.md
  backend/plan/DB명세서,API설계.md
  backend/plan/MYSQL설치과정.md
  backend/plan/sql/todo_table_create_20220407.sql
  backend/src/main/java/com/team15/todoapi/TodoApplication.java
  backend/src/main/java/com/team15/todoapi/controller/CardController.java
  backend/src/main/java/com/team15/todoapi/controller/card/CardDto.java
  backend/src/main/java/com/team15/todoapi/domain/Card.java
  backend/src/main/java/com/team15/todoapi/repository/CardRepository.java
  backend/src/main/java/com/team15/todoapi/repository/JdbcCardRepository.java
  backend/src/main/java/com/team15/todoapi/service/CardService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  backend/src/test/java/com/team15/todoapi/TodoApplicationTests.java
Labels: review-BE

#140 [Team-09][BE] 2주차 # PR1 - Jun & Bong
  backend/.gitignore
  backend/src/main/java/com/example/backend/config/AwsS3Configuration.java
  backend/src/main/java/com/example/backend/controller/ApiResult.java
  backend/src/main/java/com/example/backend/controller/card/CardController.java
  backend/src/main/java/com/example/backend/controller/card/CardReadController.java
  backend/src/main/java/com/example/backend/controller/card/dto/Author.java
  backend/src/main/java/com/example/backend/controller/card/dto/CardDto.java
  backend/src/main/java/com/example/backend/controller/card/dto/CompletedItem.java
  backend/src/main/java/com/example/backend/controller/card/dto/DailyPlan.java
  backend/src/main/java/com/example/backend/controller/card/dto/ProgressingItem.java
  backend/src/main/java/com/example/backend/controller/card/dto/Task.java
  backend/src/main/java/com/example/backend/controller/card/dto/TodoItem.java
  backend/src/main/java/com/example/backend/controller/column/ColumnController.java
  backend/src/main/java/com/example/backend/controller/history/HistoryController.java
  backend/src/main/java/com/example/backend/controller/history/HistoryQueryHelper.java
  backend/src/main/java/com/example/backend/controller/history/HistoryRead.java
  backend/src/main/java/com/example/backend/controller/history/HistoryRepository.java
  backend/src/main/java/com/example/backend/controller/history/HistoryResponse.java
  backend/src/main/java/com/example/backend/controller/history/HistorySaveRequest.java
  backend/src/main/java/com/example/backend/controller/history/HistoryService.java
  backend/src/main/java/com/example/backend/domain/card/Card.java
  backend/src/main/java/com/example/backend/domain/card/CardType.java
  backend/src/main/java/com/example/backend/domain/column/Column.java
  backend/src/main/java/com/example/backend/domain/history/Action.java
  backend/src/main/java/com/example/backend/domain/history/History.java
  backend/src/main/java/com/example/backend/repository/Command.java
  backend/src/main/java/com/example/backend/repository/card/CardRepository.java
  backend/src/main/java/com/example/backend/repository/card/CardRepositoryHelper.java
  backend/src/main/java/com/example/backend/repository/card/jdbc/CardJdbcRepository.java
  backend/src/main/java/com/example/backend/repository/card/jdbc/CardReadRepository.java
  backend/src/main/java/com/example/backend/repository/column/ColumnRepository.java
  backend/src/main/java/com/example/backend/repository/column/jdbc/ColumnJdbcRepository.java
  backend/src/main/java/com/example/backend/service/card/CardReadService.java
  backend/src/main/java/com/example/backend/service/card/CardService.java
  backend/src/main/java/com/example/backend/service/column/ColumnService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/main/resources/tables.sql
  backend/src/test/java/com/example/backend/controller/card/CardReadControllerTest.java
Labels: review-BE

#143 [Team-10][BE] Todo-list 2주차 PR #3
  BE/build.gradle
  BE/src/main/java/kr/codesquad/todolist/config/SwaggerConfig.java
  BE/src/main/java/kr/codesquad/todolist/controller/CardController.java
  BE/src/main/java/kr/codesquad/todolist/controller/mockupController.java
  BE/src/main/java/kr/codesquad/todolist/domain/Card.java
  BE/src/main/java/kr/codesquad/todolist/domain/Section.java
  BE/src/main/java/kr/codesquad/todolist/dto/CardDto.java
  BE/src/main/java/kr/codesquad/todolist/dto/card/CardResponse.java
  BE/src/main/java/kr/codesquad/todolist/dto/card/CreateCardRequest.java
  BE/src/main/java/kr/codesquad/todolist/dto/card/MotionInfo.java
  BE/src/main/java/kr/codesquad/todolist/dto/card/UpdateCardRequest.java
  BE/src/main/java/kr/codesquad/todolist/dto/section/CardsOfSection.java
  BE/src/main/java/kr/codesquad/todolist/repository/CardRepository.java
  BE/src/main/java/kr/codesquad/todolist/repository/JdbcCardRepository.java
  BE/src/main/java/kr/codesquad/todolist/service/CardService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/kr/codesquad/todolist/controller/CardControllerTest.java
  BE/src/test/java/kr/codesquad/todolist/repository/JdbcCardRepositoryTest.java
  BE/src/test/java/kr/codesquad/todolist/service/CardServiceTest.java
Labels: review-BE

#148 [team29][FE] 카드 등록 추가
  .eslintrc.json
  index.html
  package-lock.json
  package.json
  src/Views/Modal.js
  src/Views/TodoCard.js
  src/Views/TodoColumn.js
  src/Views/TodoColumns.js
  src/app.js
  src/store.js
  src/utils/utils.js
  src/webdb.js
  styles/main.scss
  styles/scss/components/_modal.scss
  styles/scss/components/_todo-column.scss
  styles/scss/components/_todo-list.scss
  styles/scss/constants/_colors.scss
  webpack.config.js
Labels: review-FE

#131 [Team-21 BE Ikjo & Hanse] Todo-List 프로젝트 2주차(수요일) 코드 리뷰 요청
  BE/src/main/java/com/todolist/controller/UserLogController.java
  BE/src/main/java/com/todolist/controller/WorkController.java
  BE/src/main/java/com/todolist/domain/UserLog.java
  BE/src/main/java/com/todolist/domain/Work.java
  BE/src/main/java/com/todolist/domain/WorkLog.java
  BE/src/main/java/com/todolist/dto/ColumnListDto.java
  BE/src/main/java/com/todolist/dto/UserLogDto.java
  BE/src/main/java/com/todolist/dto/UserLogListDto.java
  BE/src/main/java/com/todolist/dto/WorkCreationDto.java
  BE/src/main/java/com/todolist/dto/WorkDto.java
  BE/src/main/java/com/todolist/dto/WorkListDto.java
  BE/src/main/java/com/todolist/dto/WorkLogDto.java
  BE/src/main/java/com/todolist/dto/WorkLogListDto.java
  BE/src/main/java/com/todolist/dto/WorkMovementDto.java
  BE/src/main/java/com/todolist/dto/WorkRequestFormDto.java
  BE/src/main/java/com/todolist/repository/CategoryRepository.java
  BE/src/main/java/com/todolist/repository/UserLogRepository.java
  BE/src/main/java/com/todolist/repository/WorkLogRepository.java
  BE/src/main/java/com/todolist/repository/WorkRepository.java
  BE/src/main/java/com/todolist/service/UserLogService.java
  BE/src/main/java/com/todolist/service/WorkLogService.java
  BE/src/main/java/com/todolist/service/WorkService.java
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: review-BE

#159 [team-17][BE] To-do list 프로젝트 2주차 PR#3
  backend/build.gradle
  backend/src/main/java/com/codesquad/todolist/card/Card.java
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardCreateRequest.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardMoveRequest.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardResponse.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardUpdateRequest.java
  backend/src/main/java/com/codesquad/todolist/column/Column.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnController.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnRepository.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnService.java
  backend/src/main/java/com/codesquad/todolist/column/dto/ColumnResponse.java
  backend/src/main/java/com/codesquad/todolist/config/DateTimeConfig.java
  backend/src/main/java/com/codesquad/todolist/config/SwaggerConfig.java
  backend/src/main/java/com/codesquad/todolist/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/codesquad/todolist/history/HistoryController.java
  backend/src/main/java/com/codesquad/todolist/history/HistoryRepository.java
  backend/src/main/java/com/codesquad/todolist/history/HistoryService.java
  backend/src/main/java/com/codesquad/todolist/history/ModifiedFieldRepository.java
  backend/src/main/java/com/codesquad/todolist/history/domain/Action.java
  backend/src/main/java/com/codesquad/todolist/history/domain/Field.java
  backend/src/main/java/com/codesquad/todolist/history/domain/History.java
  backend/src/main/java/com/codesquad/todolist/history/domain/ModifiedField.java
  backend/src/main/java/com/codesquad/todolist/history/dto/HistoryResponse.java
  backend/src/main/java/com/codesquad/todolist/history/dto/ModifiedFieldResponse.java
  backend/src/main/java/com/codesquad/todolist/util/page/Criteria.java
  backend/src/main/java/com/codesquad/todolist/util/page/Slice.java
  backend/src/main/resources/application-local.properties
  backend/src/main/resources/application-prod.properties
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/codesquad/todolist/SetUp.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardSetUp.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
  backend/src/test/java/com/codesquad/todolist/column/unit/ColumnServiceTest.java
  backend/src/test/java/com/codesquad/todolist/history/integration/HistoryControllerTest.java
  backend/src/test/java/com/codesquad/todolist/history/integration/HistoryRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/history/integration/ModifiedFieldRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/history/unit/HistoryControllerTest.java
  backend/src/test/java/com/codesquad/todolist/history/unit/HistoryServiceTest.java
Labels: review-BE

#154 [team-31][BE K&Yan] To-do list 그룹 프로젝트 2주차(수) 3번째 PR
  todo-list/build.gradle
  todo-list/src/main/java/com/todolist/project/domain/ActionStatus.java
  todo-list/src/main/java/com/todolist/project/domain/card/Card.java
  todo-list/src/main/java/com/todolist/project/domain/card/CardRepository.java
  todo-list/src/main/java/com/todolist/project/domain/log/Log.java
  todo-list/src/main/java/com/todolist/project/domain/log/LogRepository.java
  todo-list/src/main/java/com/todolist/project/service/CardService.java
  todo-list/src/main/java/com/todolist/project/service/LogService.java
  todo-list/src/main/java/com/todolist/project/web/CardController.java
  todo-list/src/main/java/com/todolist/project/web/LogController.java
  todo-list/src/main/java/com/todolist/project/web/dto/CardAddDto.java
  todo-list/src/main/java/com/todolist/project/web/dto/CardListDto.java
  todo-list/src/main/java/com/todolist/project/web/dto/CardUpdateDto.java
  todo-list/src/main/java/com/todolist/project/web/dto/LogListDto.java
  todo-list/src/main/resources/application-dev.yml
  todo-list/src/main/resources/application-prod.yml
  todo-list/src/main/resources/application.properties
  todo-list/src/main/resources/data.sql
  todo-list/src/main/resources/schema.sql
  todo-list/src/test/java/com/todolist/project/domain/card/CardRepositoryTest.java
  todo-list/src/test/java/com/todolist/project/web/CardControllerTest.java
Labels: review-BE

#146 [team-13][BE] To-do list 그룹 프로젝트 2주차(수) 3번째 PR
  Server/build.gradle
  Server/src/main/java/com/todolist/controller/CardController.java
  Server/src/main/java/com/todolist/controller/UserController.java
  Server/src/main/java/com/todolist/domain/dto/CardAllShowDto.java
  Server/src/main/java/com/todolist/domain/dto/CardCreateDto.java
  Server/src/main/java/com/todolist/domain/dto/CardPatchDto.java
  Server/src/main/java/com/todolist/exception/ExceptionType.java
  Server/src/main/java/com/todolist/exception/GlobalException.java
  Server/src/main/java/com/todolist/exception/GlobalExceptionHandler.java
  Server/src/main/java/com/todolist/exception/NotFoundCardException.java
  Server/src/main/java/com/todolist/exception/RestResponse.java
  Server/src/main/java/com/todolist/repository/CardRepository.java
  Server/src/main/java/com/todolist/service/CardService.java
  Server/src/main/resources/schema.sql
Labels: review-BE

#129 [Team-28] [FE] 함수로 컴포넌트 구성 & 백엔드 1차 완성 및 연결
  dist/main.js
  jsconfig.json
  package-lock.json
  server/.gitignore
  server/models/card.js
  server/models/log.js
  server/route.rest
  server/routes/columns.js
  server/routes/logs.js
  server/server.js
  src/app.js
  src/app.scss
  src/common/util.js
  src/common/variable.js
  src/components/header/Header.js
  src/components/header/Header.scss
  src/components/header/menu/Menu.js
  src/components/header/menu/Menu.scss
  src/components/main/Main.js
  src/components/main/column-container/Column/Column.js
  src/components/main/column-container/Column/Column.scss
  src/components/main/column-container/Column/card/Card.js
  src/components/main/column-container/Column/card/alert/Alert.js
  src/components/main/column-container/Column/card/alert/Alert.scss
  src/components/main/column-container/ColumnContainer.js
  src/index.html
  src/stores/columnStore.js
  src/stores/menuStore.js
Labels: review-FE

#149 [team-14][BE] To-do list 그룹 프로젝트 2주차(수) PR
  backend/build.gradle
  backend/src/main/java/com/example/backend/domain/ActionType.java
  backend/src/main/java/com/example/backend/domain/Card.java
  backend/src/main/java/com/example/backend/domain/ColumnName.java
  backend/src/main/java/com/example/backend/domain/Log.java
  backend/src/main/java/com/example/backend/domain/repository/CardJdbcTemplateRepository.java
  backend/src/main/java/com/example/backend/domain/repository/CardRepository.java
  backend/src/main/java/com/example/backend/domain/repository/LogJdbcTemplateRepository.java
  backend/src/main/java/com/example/backend/service/CardService.java
  backend/src/main/java/com/example/backend/service/LogService.java
  backend/src/main/java/com/example/backend/web/controller/CardsController.java
  backend/src/main/java/com/example/backend/web/controller/LogsController.java
  backend/src/main/java/com/example/backend/web/dto/CardListResponseDto.java
  backend/src/main/java/com/example/backend/web/dto/CardUpdateRequestDto.java
  backend/src/main/java/com/example/backend/web/dto/Column.java
  backend/src/main/java/com/example/backend/web/dto/Columns.java
  backend/src/main/java/com/example/backend/web/dto/LogListResponseDto.java
  backend/src/main/java/com/example/backend/web/dto/LogSaveRequestDto.java
  backend/src/main/resources/application-develop.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
Labels: review-BE

#174 [team35 bangtae & 난정] 2주차 수요일 PR
  js/components/model/scheduleModel.js
  js/components/schedule/scheduleCard.js
  js/components/schedule/scheduleCardCount.js
  js/components/schedule/scheduleCardDrag.js
  js/components/schedule/scheduleColumn.js
  js/components/schedule/scheduleDeleteConfirm.js
  js/components/schedule/scheduleEditCard.js
  js/components/schedule/scheduleRegisterCard.js
  js/index.js
  js/utils.js
  styles/_global.scss
  styles/_schedule.scss
  styles/style.css
Labels: review-FE

#137 [Team-18] [FE] History 메뉴, Card 컴포넌트 추가
  data.json
  package.json
  src/api.js
  src/app.js
  src/components/Cards.js
  src/components/Column.js
  src/components/Header.js
  src/components/History.js
  src/components/Menu.js
  src/style/images/cross.png
  src/style/images/delete-gray3.png
  src/style/images/delete-red.png
  src/style/scss/Cards.scss
  src/style/scss/Column.scss
  src/style/scss/Header.scss
  src/style/scss/Menu.scss
  src/style/scss/reset.scss
  src/style/scss/style.scss
Labels: review-FE

#168 [team-10][iOS-1] EditCardView 구현, 셀 드래그 앤 드랍, 스와이프 이벤트 구현 및 네트워크 통신을 위한 객체 구현
  ToDoList/ToDoList.xcodeproj/project.pbxproj
  ToDoList/ToDoList/Controller/CardListViewController.swift
  ToDoList/ToDoList/Controller/EditCardViewController.swift
  ToDoList/ToDoList/Controller/MainViewController.swift
  ToDoList/ToDoList/Info.plist
  ToDoList/ToDoList/Model/Caption.swift
  ToDoList/ToDoList/Model/Card.swift
  ToDoList/ToDoList/Model/CardFactory.swift
  ToDoList/ToDoList/Model/CardList.swift
  ToDoList/ToDoList/Model/CardManager.swift
  ToDoList/ToDoList/Model/ID.swift
  ToDoList/ToDoList/Model/NetworkManager.swift
  ToDoList/ToDoList/Model/NetworkTarget.swift
  ToDoList/ToDoList/Model/protocols/CardManagable.swift
  ToDoList/ToDoList/Model/protocols/Cardable.swift
  ToDoList/ToDoList/Model/protocols/ModelFactoriable.swift
  ToDoList/ToDoList/Model/protocols/ModelFactoryBase.swift
  ToDoList/ToDoList/Model/protocols/NetworkTargetable.swift
  ToDoList/ToDoList/View/CardListTableViewCell.swift
  ToDoList/ToDoList/View/CardListView.xib
  ToDoList/ToDoList/View/EditCardView.swift
  ToDoList/ToDoList/View/EditCardView.xib
Labels: review-iOS

#177 [Team-11] Eddy & Jason: 할일 조회, 추가, 삭제 기능 추가
  iOS/todo-list/todo-list.xcodeproj/project.pbxproj
  iOS/todo-list/todo-list/Common/DataPrettyPrint.swift
  iOS/todo-list/todo-list/Common/DateFormatter.swift
  iOS/todo-list/todo-list/Common/Observerble.swift
  iOS/todo-list/todo-list/Common/SystemLog.swift
  iOS/todo-list/todo-list/Model/Log.swift
  iOS/todo-list/todo-list/Model/LogManager.swift
  iOS/todo-list/todo-list/Model/NetworkManager.swift
  iOS/todo-list/todo-list/Model/Task.swift
  iOS/todo-list/todo-list/Model/TaskStorage.swift
  iOS/todo-list/todo-list/Resource/Base.lproj/Main.storyboard
  iOS/todo-list/todo-list/Resource/dummyLogResponse.json
  iOS/todo-list/todo-list/Resource/dummyTaskResponse.json
  iOS/todo-list/todo-list/UseCases/NetworkManager.swift
  iOS/todo-list/todo-list/UseCases/TaskManager.swift
  iOS/todo-list/todo-list/View Model/ColumnViewModel.swift
  iOS/todo-list/todo-list/View Model/LogViewModel.swift
  iOS/todo-list/todo-list/View/TaskTableViewCell.swift
  iOS/todo-list/todo-list/ViewController/ActivityRecoderController.swift
  iOS/todo-list/todo-list/ViewController/KanbanViewController.swift
  iOS/todo-list/todo-listTests/ColumnViewModelTests.swift
  iOS/todo-list/todo-listTests/DecodingEcodingTests.swift
  iOS/todo-list/todo-listTests/LogManagerTests.swift
  iOS/todo-list/todo-listTests/NetworkManagerTests.swift
  iOS/todo-list/todo-listTests/TaskManagerTests.swift
  iOS/todo-list/todo-listTests/todo_listTests.swift
Labels: review-iOS

#160 [Team-25] [FE] TODO LIST 2주차 첫번째 PR
  db.json
  index.html
  package-lock.json
  package.json
  src/client/js/api/columnApi.js
  src/client/js/api/index.js
  src/client/js/api/taskApi.js
  src/client/js/api/userApi.js
  src/client/js/app.js
  src/client/js/components/Action.js
  src/client/js/components/ActionLayer.js
  src/client/js/components/Alert.js
  src/client/js/components/Card.js
  src/client/js/components/Column.js
  src/client/js/components/Header.js
  src/client/js/components/InputCard.js
  src/client/js/core/Component.js
  src/client/js/render/index.js
  src/client/js/store/ActionStore.js
  src/client/js/store/actionStore.js
  src/client/js/store/columnStore.js
  src/client/js/store/index.js
  src/client/js/store/store.js
  src/client/js/store/taskStore.js
  src/client/js/store/userStore.js
  src/client/js/utils/index.js
  src/client/style/_extends.scss
  src/client/style/style.scss
  src/server/middleware.js
Labels: review-FE

#178 [team-01][BE] API - Todo 생성하기 기능
  BE/build.gradle
  BE/src/main/java/codesquad/be/todoserver/controller/TodoController.java
  BE/src/main/java/codesquad/be/todoserver/controller/TodoDtoMapper.java
  BE/src/main/java/codesquad/be/todoserver/controller/model/RegisterTodoDto.java
  BE/src/main/java/codesquad/be/todoserver/domain/History.java
  BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
  BE/src/main/java/codesquad/be/todoserver/repository/HistoryJdbcRepository.java
  BE/src/main/java/codesquad/be/todoserver/repository/HistoryRepository.java
  BE/src/main/java/codesquad/be/todoserver/repository/TodoJdbcRepository.java
  BE/src/main/java/codesquad/be/todoserver/repository/TodoRepository.java
  BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
  BE/src/test/java/codesquad/be/todoserver/TodosApiAcceptanceTest.java
  BE/src/test/java/codesquad/be/todoserver/service/TodoServiceTest.java
Labels: review-BE

#164 [team-30][FE] 협업 프로젝트 2주차 - 1
  .gitignore
  babel.config.json
  public/bundle.js
  public/index.html
  server/db.json
  src/app.html
  src/app.js
  src/js/controller/MainController.js
  src/js/model/Store.js
  src/js/view/CardView.js
  src/js/view/ColumnView.js
  src/js/view/EmptyCardView.js
  src/style/header.scss
  src/style/sideMenuBar.scss
  src/style/style.scss
  src/style/taskCard.scss
  src/style/taskColumn.scss
  src/util/Util.js
  src/util/domUtil.js
  test.css
  test.html
  test.js
  webpack.config.js
Labels: review-FE

#169 [Team-32][FE] 2주차 #1 PR - Muffin & Jinnie review-FE
  README.md
  app.js
  components/Modal.js
  components/Todo.js
  components/TodoColumn.js
  components/TodoEdit.js
  components/TodoEditTemplate.js
  components/TodoInput.js
  components/TodoNotice.js
  constants/modal.js
  index.css
  index.html
  package-lock.json
  package.json
  server/server.js
  server/todos.json
  style/_modal.scss
  style/_utilities.scss
  style/_variables.scss
  style/index.scss
  utils/action.js
  utils/api.js
  utils/dom.js
  utils/eventDragHandler.js
  utils/handleStyle.js
  utils/localStorage.js
Labels: review-FE

#153 [team_33] 2주차 수요일 pr
  client/src/index.html
  client/src/js/main.js
  client/src/js/template.js
  client/src/js/todos.js
  client/src/js/todos/addCard.js
  client/src/js/todos/deleteCard.js
  client/src/js/todos/dragAndDrop.js
  client/src/js/todos/initTodos.js
  client/src/js/todos/menuBar.js
  client/src/js/todos/template.js
  client/src/js/todos/updateCard.js
  client/src/js/util.js
  client/src/styles/_common.scss
  client/src/styles/body/_body.scss
  client/src/styles/header/_headerBar.scss
Labels: review-FE

#147 [team-16][iOS] 2주차 메모 수정 팝업 뷰, 메모 드래그/드롭, 네트워크 계층 구성
  todo-list-ios/TODOList/TODOList.xcodeproj/project.pbxproj
  todo-list-ios/TODOList/TODOList/Common/EndPoint.swift
  todo-list-ios/TODOList/TODOList/Controllers/MainViewController.swift
  todo-list-ios/TODOList/TODOList/Controllers/MemoCanvasViewController.swift
  todo-list-ios/TODOList/TODOList/Controllers/MemoContainerType.swift
  todo-list-ios/TODOList/TODOList/Controllers/MemoContainerViewController.swift
  todo-list-ios/TODOList/TODOList/Controllers/PopupViewController.swift
  todo-list-ios/TODOList/TODOList/Data/Network/HTTPRequestHandler.swift
  todo-list-ios/TODOList/TODOList/Data/Network/Model/CommonResponseType.swift
  todo-list-ios/TODOList/TODOList/Data/Network/Model/MemoPostData.swift
  todo-list-ios/TODOList/TODOList/Data/Network/Model/MemoResponse.swift
  todo-list-ios/TODOList/TODOList/Domain/Entities/HistoryEntity.swift
  todo-list-ios/TODOList/TODOList/Domain/Entities/MemoEntity.swift
  todo-list-ios/TODOList/TODOList/Domain/MemoStatus.swift
  todo-list-ios/TODOList/TODOList/Domain/UseCases/HistoryUseCase.swift
  todo-list-ios/TODOList/TODOList/Domain/UseCases/MemoUseCase.swift
  todo-list-ios/TODOList/TODOList/Models/Memo/Memo.swift
  todo-list-ios/TODOList/TODOList/Views/History/SideView.swift
  todo-list-ios/TODOList/TODOList/Views/Memo/MemoCanvasView.swift
  todo-list-ios/TODOList/TODOList/Views/Memo/MemoContainerView.swift
  todo-list-ios/TODOList/TODOList/Views/Memo/MemoTableViewCell.swift
  todo-list-ios/TODOList/TODOList/Views/Memo/PopupCardView.swift
  todo-list-ios/TODOList/TODOList/Views/Xib/PopupCardView.xib
Labels: review-iOS

#150 [team26][FE] Todo-list 2주차
  .gitignore
  FE/package.json
  FE/src/app.js
  FE/src/components/CardModificationForm.js
  FE/src/components/Column.js
  FE/src/components/Columns.js
  FE/src/components/Histories.js
  FE/src/components/HistoryCard.js
  FE/src/components/Modal.js
  FE/src/components/TaskCard.js
  FE/src/dummyData.js
  FE/src/index.html
  FE/src/store.js
  FE/src/styles/_backgrounds.scss
  FE/src/styles/_colors.scss
  FE/src/styles/_header.scss
  FE/src/styles/_history.scss
  FE/src/styles/_modal.scss
  FE/src/styles/_reset.scss
  FE/src/styles/_task.scss
  FE/src/styles/_typography.scss
  FE/src/styles/_utils.scss
  FE/src/styles/_work.scss
  FE/src/styles/main.scss
  FE/src/utils.js
  FE/webpack.config.js
Labels: review-FE

#141 [Team 17][FE] Todo List 2주차 PR1
  frontend/index.html
  frontend/src/js/Alert/AlertView.js
  frontend/src/js/Controller/Controller.js
  frontend/src/js/Header/Model.js
  frontend/src/js/Header/View.js
  frontend/src/js/Header/main.js
  frontend/src/js/History/View.js
  frontend/src/js/History/main.js
  frontend/src/js/Todo/Card/Model.js
  frontend/src/js/Todo/Card/View.js
  frontend/src/js/Todo/Card/main.js
  frontend/src/js/Todo/Column/Model.js
  frontend/src/js/Todo/Column/View.js
  frontend/src/js/Todo/Column/main.js
  frontend/src/js/Todo/Model.js
  frontend/src/js/Todo/View.js
  frontend/src/js/Todo/main.js
  frontend/src/js/Utils/createTemplate.js
  frontend/src/js/Utils/template.js
  frontend/src/js/app.js
  frontend/src/js/dragNdrop.js
  frontend/src/js/utils/createTemplate.js
  frontend/src/scss/style.scss
Labels: review-FE

#170 [team-19] Todo-list 2주차 첫번째 코드리뷰 요청
  client/src/js/constants/imagePath.js
  client/src/js/constants/urlPath.js
  client/src/js/header/view.js
  client/src/js/main/alertDelete.js
  client/src/js/main/index.js
  client/src/js/main/list.js
  client/src/js/main/task.js
  client/src/js/main/taskDragHandler.js
  client/src/js/sidebar/view.js
  client/src/js/store/activationStore.js
  client/src/js/store/todoListStore.js
  client/src/js/store/todolistStore.js
  client/src/js/utils/utils.js
  client/src/style/css/style.css
  client/src/style/css/style.css.map
  client/src/style/scss/abstracts/_variables.scss
  client/src/style/scss/layout/main/_column-task-list.scss
  client/src/style/scss/layout/main/_delete-menu.scss
  client/src/style/scss/style.scss
  server/data/db.json
Labels: review-FE

#185 [team-15][BE] 2주차 첫번째 PR 요청입니다.
  .idea/sonarlint/issuestore/2/1/21d4b1ec4e3be89735ba8533a58eee07a372667a
  .idea/sonarlint/issuestore/8/e/8ec9a00bfd09b3190ac6b22251dbb1aa95a0579d
  .idea/sonarlint/issuestore/8/f/8f5034e22a34471e9dd3ec57de230ade8e0e3332
  .idea/sonarlint/issuestore/e/9/e99a472fc25b737a8aa8dbaee48305ef6c505c57
  .idea/sonarlint/issuestore/index.pb
  .idea/vcs.xml
  .idea/workspace.xml
  backend/README.md
  backend/build.gradle
  backend/plan/MYSQL설치과정.md
  backend/src/main/java/com/team15/todoapi/controller/CardController.java
  backend/src/main/java/com/team15/todoapi/controller/HistoryController.java
  backend/src/main/java/com/team15/todoapi/controller/card/CardDto.java
  backend/src/main/java/com/team15/todoapi/controller/card/CardRequest.java
  backend/src/main/java/com/team15/todoapi/controller/card/CardResponse.java
  backend/src/main/java/com/team15/todoapi/controller/history/HistoryResponse.java
  backend/src/main/java/com/team15/todoapi/domain/Card.java
  backend/src/main/java/com/team15/todoapi/domain/History.java
  backend/src/main/java/com/team15/todoapi/domain/Member.java
  backend/src/main/java/com/team15/todoapi/repository/CardRepository.java
  backend/src/main/java/com/team15/todoapi/repository/HistoryRepository.java
  backend/src/main/java/com/team15/todoapi/repository/JdbcCardRepository.java
  backend/src/main/java/com/team15/todoapi/repository/JdbcHistoryRepository.java
  backend/src/main/java/com/team15/todoapi/repository/JdbcMemberRepository.java
  backend/src/main/java/com/team15/todoapi/repository/MemberRepository.java
  backend/src/main/java/com/team15/todoapi/service/CardService.java
  backend/src/main/java/com/team15/todoapi/service/HistoryService.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/logback.xml
Labels: review-BE

#167 [Team-06][BE Shine & 땃쥐] 2022/04/13 3차 PR
  BE/README.md
  BE/src/main/java/codesquad/todo/domain/column/Column.java
  BE/src/main/java/codesquad/todo/domain/column/ColumnRepository.java
  BE/src/main/java/codesquad/todo/domain/column/MemoryColumnRepository.java
  BE/src/main/java/codesquad/todo/domain/history/History.java
  BE/src/main/java/codesquad/todo/domain/history/HistoryRepository.java
  BE/src/main/java/codesquad/todo/domain/history/HistoryType.java
  BE/src/main/java/codesquad/todo/domain/history/MemoryHistoryRepository.java
  BE/src/main/java/codesquad/todo/domain/user/MemoryUserRepository.java
  BE/src/main/java/codesquad/todo/domain/user/User.java
  BE/src/main/java/codesquad/todo/domain/user/UserRepository.java
  BE/src/main/java/codesquad/todo/domain/work/MemoryWorkRepository.java
  BE/src/main/java/codesquad/todo/domain/work/Work.java
  BE/src/main/java/codesquad/todo/domain/work/WorkRepository.java
  BE/src/main/java/codesquad/todo/service/ColumnService.java
  BE/src/main/java/codesquad/todo/service/HistoryService.java
  BE/src/main/java/codesquad/todo/service/WorkService.java
  BE/src/main/java/codesquad/todo/web/history/HistoryController.java
  BE/src/main/java/codesquad/todo/web/history/dto/HistoryDetailResponse.java
  BE/src/main/java/codesquad/todo/web/history/dto/HistoryListResponse.java
  BE/src/main/java/codesquad/todo/web/works/WorkController.java
  BE/src/main/java/codesquad/todo/web/works/dto/WorkDeleteResponse.java
  BE/src/main/java/codesquad/todo/web/works/dto/WorkDetailResponse.java
  BE/src/main/java/codesquad/todo/web/works/dto/WorkListResponse.java
  BE/src/main/java/codesquad/todo/web/works/dto/WorkMoveRequest.java
  BE/src/main/java/codesquad/todo/web/works/dto/WorkSaveRequest.java
  BE/src/main/java/codesquad/todo/web/works/dto/WorkSaveResponse.java
  BE/src/main/java/codesquad/todo/web/works/dto/WorkUpdateRequest.java
  BE/src/test/java/codesquad/todo/domain/work/MemoryWorkRepositoryTest.java
Labels: review-BE

#133 [Team-05 BE nathan & 피오] Todolist 기능 구현 및 배포, api 문서화 진행
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/team05/todolist/TodoListApplication.java
  backend/src/main/java/com/team05/todolist/config/AopConfiguration.java
  backend/src/main/java/com/team05/todolist/config/SwaggerConfiguration.java
  backend/src/main/java/com/team05/todolist/controller/CardController.java
  backend/src/main/java/com/team05/todolist/controller/HomeController.java
  backend/src/main/java/com/team05/todolist/domain/Card.java
  backend/src/main/java/com/team05/todolist/domain/Event.java
  backend/src/main/java/com/team05/todolist/domain/Log.java
  backend/src/main/java/com/team05/todolist/domain/dto/CardDTO.java
  backend/src/main/java/com/team05/todolist/domain/dto/ClassifiedCardsDTO.java
  backend/src/main/java/com/team05/todolist/domain/dto/CreateCardDTO.java
  backend/src/main/java/com/team05/todolist/domain/dto/ListResponseDTO.java
  backend/src/main/java/com/team05/todolist/domain/dto/LogDTO.java
  backend/src/main/java/com/team05/todolist/domain/dto/MoveCardDTO.java
  backend/src/main/java/com/team05/todolist/domain/dto/ResponseDTO.java
  backend/src/main/java/com/team05/todolist/domain/dto/UpdateCardDTO.java
  backend/src/main/java/com/team05/todolist/repository/CardRepository.java
  backend/src/main/java/com/team05/todolist/repository/JdbcCardRepository.java
  backend/src/main/java/com/team05/todolist/repository/JdbcLogRepository.java
  backend/src/main/java/com/team05/todolist/repository/LogRepository.java
  backend/src/main/java/com/team05/todolist/service/CardService.java
  backend/src/main/java/com/team05/todolist/service/LogService.java
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/team05/todolist/repository/JdbcCardRepositoryTest.java
Labels: review-BE

#130 [Team-13] 서버에서 가져온 데이터를 화면에 보여주기
  Client/iOS/.gitignore
  Client/iOS/TodoList.xcodeproj/project.pbxproj
  Client/iOS/TodoList.xcodeproj/project.xcworkspace/xcuserdata/sanghwiback.xcuserdatad/UserInterfaceState.xcuserstate
  Client/iOS/TodoList/AppDelegate.swift
  Client/iOS/TodoList/Assets.xcassets/Black.colorset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/Gray4.colorset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/button_accent_default.colorset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/button_accent_disabled.colorset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/button_accent_hover.colorset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/button_normal_default.colorset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/button_normal_hover.colorset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/gray3.colorset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/gray5.colorset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/gray6.colorset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/icon_close.imageset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/icon_close.imageset/icon_close-1.png
  Client/iOS/TodoList/Assets.xcassets/icon_close.imageset/icon_close-2.png
  Client/iOS/TodoList/Assets.xcassets/icon_close.imageset/icon_close-3.png
  Client/iOS/TodoList/Assets.xcassets/icon_plus.imageset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/icon_plus.imageset/icon_plus-1.png
  Client/iOS/TodoList/Assets.xcassets/icon_plus.imageset/icon_plus-2.png
  Client/iOS/TodoList/Assets.xcassets/icon_plus.imageset/icon_plus-3.png
  Client/iOS/TodoList/Assets.xcassets/icon_plus_highlighted.imageset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/icon_plus_highlighted.imageset/icon_plus_highlighted-1.png
  Client/iOS/TodoList/Assets.xcassets/icon_plus_highlighted.imageset/icon_plus_highlighted-2.png
  Client/iOS/TodoList/Assets.xcassets/icon_plus_highlighted.imageset/icon_plus_highlighted-3.png
  Client/iOS/TodoList/Assets.xcassets/red.colorset/Contents.json
  Client/iOS/TodoList/Assets.xcassets/white.colorset/Contents.json
  Client/iOS/TodoList/Base.lproj/Main.storyboard
  Client/iOS/TodoList/Cells/TodoTableViewCell.swift
  Client/iOS/TodoList/Cells/TodoTableViewCell.xib
  Client/iOS/TodoList/DB/CoreData/Model.xcdatamodeld/Model.xcdatamodel/contents
  Client/iOS/TodoList/DB/CoreData/TaskBoard+CoreDataClass.swift
  Client/iOS/TodoList/DB/CoreData/TaskBoard+CoreDataProperties.swift
  Client/iOS/TodoList/DB/PersistenceProvider.swift
  Client/iOS/TodoList/Network/CardsFetchingDataTask.swift
  Client/iOS/TodoList/Network/CardsFetchingDebugDataTask.swift
  Client/iOS/TodoList/Network/ResourcesNetwork/CardData.swift
  Client/iOS/TodoList/Network/ResourcesNetwork/CardMap.swift
  Client/iOS/TodoList/Repository/CardDataMiddleWare.swift
  Client/iOS/TodoList/View/TodoRepositoryRespondWrapper.swift
  Client/iOS/TodoList/View/TodoTableView.swift
  Client/iOS/TodoList/ViewController.swift
  Client/iOS/TodoList/ViewControllers/CompletedTodoViewController.swift
  Client/iOS/TodoList/ViewControllers/ProgressTodoViewController.swift
  Client/iOS/TodoList/ViewControllers/TodoViewController.swift
  Client/iOS/TodoList/ViewControllers/ViewController.swift
  Client/iOS/TodoListTests/CardAPITests.swift
Labels: review-iOS

#172 [Team04] Stitch&스타크 - 드래그 앤 드롭, Swipe, Retrofit2 설정 및 조회, 수정 API 기능 구현
  android/app/src/main/java/com/example/todolist/model/request/ModifyTaskRequest.kt
  android/app/src/main/java/com/example/todolist/model/request/TaskRequest.kt
  android/app/src/main/java/com/example/todolist/model/response/TasksResponse.kt
  android/app/src/main/java/com/example/todolist/network/RetrofitAPI.kt
  android/app/src/main/java/com/example/todolist/network/Service.kt
  android/app/src/main/java/com/example/todolist/repository/TaskDataSource.kt
  android/app/src/main/java/com/example/todolist/repository/TaskRemoteDataSource.kt
  android/app/src/main/java/com/example/todolist/repository/TaskRemoteRepository.kt
  android/app/src/main/java/com/example/todolist/repository/TaskRepository.kt
  android/app/src/main/java/com/example/todolist/ui/ItemTouchCallback.kt
  android/app/src/main/java/com/example/todolist/ui/ItemTouchHelperListener.kt
  android/app/src/main/java/com/example/todolist/ui/MainActivity.kt
  android/app/src/main/java/com/example/todolist/ui/NewTaskDialogFragment.kt
  android/app/src/main/java/com/example/todolist/ui/TaskAdapter.kt
  android/app/src/main/java/com/example/todolist/ui/TaskRemoteViewModel.kt
  android/app/src/main/java/com/example/todolist/ui/TaskViewModel.kt
  android/app/src/main/java/com/example/todolist/ui/UpdateTaskDialogFragment.kt
  android/app/src/main/java/com/example/todolist/ui/common/TextBindingAdapters.kt
  android/app/src/main/java/com/example/todolist/ui/common/ViewModelFactory.kt
  android/app/src/main/res/drawable/item_background_red.xml
  android/app/src/main/res/layout-sw720dp-land/activity_main.xml
  android/app/src/main/res/layout/dialog_update_card.xml
  android/app/src/main/res/layout/item_task.xml
  android/app/src/main/res/menu/menu_popup.xml
  android/app/src/main/res/values-night/strings.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: review-android

#214 ## [team29][FE] 드래그앤 드롭 구현중, 문제점
  index.html
  package-lock.json
  package.json
  src/Views/Modal.js
  src/Views/TodoCard.js
  src/Views/TodoColumn.js
  src/Views/TodoColumns.js
  src/store.js
  src/webdb.js
  styles/main.scss
  styles/scss/components/_header.scss
  styles/scss/components/_todo-column.scss
  styles/scss/components/_todo-list.scss
  styles/scss/modules/_buttons.scss
  webpack.config.js
Labels: review-FE

#189 [team-01][BE] API - Todo 삭제 기능
  BE/build.gradle
  BE/src/main/java/codesquad/be/todoserver/config/WebConfig.java
  BE/src/main/java/codesquad/be/todoserver/controller/TodoController.java
  BE/src/main/java/codesquad/be/todoserver/domain/Action.java
  BE/src/main/java/codesquad/be/todoserver/domain/History.java
  BE/src/main/java/codesquad/be/todoserver/domain/Todo.java
  BE/src/main/java/codesquad/be/todoserver/repository/HistoryJdbcRepository.java
  BE/src/main/java/codesquad/be/todoserver/repository/HistoryRepository.java
  BE/src/main/java/codesquad/be/todoserver/repository/TodoJdbcRepository.java
  BE/src/main/java/codesquad/be/todoserver/repository/TodoRepository.java
  BE/src/main/java/codesquad/be/todoserver/service/HistoryService.java
  BE/src/main/java/codesquad/be/todoserver/service/TodoService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
  BE/src/test/java/codesquad/be/todoserver/HistoriesApiAcceptanceTest.java
  BE/src/test/java/codesquad/be/todoserver/controller/TodoControllerTest.java
  BE/src/test/java/codesquad/be/todoserver/repository/TodoRepositoryTest.java
  BE/src/test/java/codesquad/be/todoserver/service/TodoServiceTest.java
  BE/src/test/resources/testDB/data.sql
  BE/src/test/resources/testDB/schema.sql
Labels: review-BE

#225 [team_33] 2주차 금요일 pr
  client/src/js/main.js
  client/src/js/todos/addCard.js
  client/src/js/todos/deleteCard.js
  client/src/js/todos/dragAndDrop.js
  client/src/js/todos/initTodos.js
  client/src/js/todos/menuBar.js
  client/src/js/todos/template.js
  client/src/js/todos/updateCard.js
  client/src/js/util.js
  client/src/styles/_common.scss
  client/src/styles/body/_body.scss
  package.json
  server/db.json
Labels: review-FE

#220 [Team 17][FE] Todo List 2주차 PR2
  frontend/src/js/Controller/Controller.js
  frontend/src/js/Header/Model.js
  frontend/src/js/History/Model.js
  frontend/src/js/History/View.js
  frontend/src/js/History/main.js
  frontend/src/js/Todo/Card/View.js
  frontend/src/js/Todo/Column/Model.js
  frontend/src/js/Todo/Column/View.js
  frontend/src/js/Todo/Column/main.js
  frontend/src/js/Todo/Model.js
  frontend/src/js/Utils/api.js
  frontend/src/js/Utils/template.js
  frontend/src/js/app.js
  frontend/src/scss/style.scss
Labels: review-FE

#208 [team-20] 네 번째 PR: 컬럼과 카드 동작
  README.md
  client/package-lock.json
  client/public/js/app.js
  client/public/js/handler/eventHandler.js
  client/public/js/handler/handler.js
  client/public/js/model/Store.js
  client/public/js/tempStorage.js
  client/public/js/utils/helpers.js
  client/public/js/views/aside/_aside.scss
  client/public/js/views/card/_card.scss
  client/public/js/views/card/card.js
  client/public/js/views/column/_column.scss
  client/public/js/views/column/column.js
  client/public/js/views/header/_header.scss
  client/public/js/views/history/_history.scss
  client/public/js/views/main/_main.scss
  client/public/js/views/main/main.js
  client/public/js/views/renderer.js
  client/public/stylesheet/util/_reset.scss
Labels: review-FE

#197 [team-14][BE] To-do list 그룹 프로젝트 2주차(금) PR
  backend/src/main/java/com/example/backend/domain/ActionType.java
  backend/src/main/java/com/example/backend/domain/Card.java
  backend/src/main/java/com/example/backend/domain/Log.java
  backend/src/main/java/com/example/backend/domain/TextCreator.java
  backend/src/main/java/com/example/backend/domain/repository/CardJdbcTemplateRepository.java
  backend/src/main/java/com/example/backend/domain/repository/CardRepository.java
  backend/src/main/java/com/example/backend/domain/repository/LogJdbcTemplateRepository.java
  backend/src/main/java/com/example/backend/service/CardService.java
  backend/src/main/java/com/example/backend/service/LogService.java
  backend/src/main/java/com/example/backend/web/controller/CardsController.java
  backend/src/main/java/com/example/backend/web/dto/CardMoveRequestDto.java
  backend/src/main/java/com/example/backend/web/dto/LogSaveRequestDto.java
Labels: review-BE

#213 [team-13][BE] To-do list 그룹 프로젝트 2주차(금) 4번째 PR
  Server/src/main/java/com/todolist/controller/CardController.java
  Server/src/main/java/com/todolist/domain/Card.java
  Server/src/main/java/com/todolist/domain/User.java
  Server/src/main/java/com/todolist/domain/dto/CardAllShowDto.java
  Server/src/main/java/com/todolist/domain/dto/CardCreateDto.java
  Server/src/main/java/com/todolist/domain/dto/CardInformationDto.java
  Server/src/main/java/com/todolist/domain/dto/CardMoveDto.java
  Server/src/main/java/com/todolist/domain/dto/CardResponseDto.java
  Server/src/main/java/com/todolist/repository/CardRepository.java
  Server/src/main/java/com/todolist/service/CardService.java
  Server/src/main/resources/schema.sql
Labels: review-BE

#218 [Team 35 nanjeong & bangtae] 2주차 금요일 PR
  Procfile
  app/dist/bundle.js
  app/dist/index.html
  app/index.html
  app/js/components/schedule/scheduleCard.js
  app/js/components/schedule/scheduleCardCount.js
  app/js/components/schedule/scheduleCardDrag.js
  app/js/components/schedule/scheduleColumn.js
  app/js/components/schedule/scheduleDeleteConfirm.js
  app/js/components/schedule/scheduleEditCard.js
  app/js/components/schedule/scheduleRegisterCard.js
  app/js/index.js
  app/js/model/history.js
  app/js/model/scheduleModel.js
  app/js/utils/styleNames.js
  app/js/utils/utils.js
  app/styles/_global.scss
  app/styles/_header.scss
  app/styles/_history.scss
  app/styles/_mixin.scss
  app/styles/_reset.scss
  app/styles/_schedule.scss
  app/styles/style.css
  app/styles/style.scss
  app/styles/user-img-sample.jpg
  dist/bundle.js
  dist/index.html
  js/components/schedule/scheduleCardCount.js
  js/index.js
  js/utils.js
  package-lock.json
  package.json
  server/db.json
  server/server.js
  styles/style.css
  webpack.config.js
Labels: review-FE

#207 [Team-28] [FE] 드래그 앤 드롭 기능 구현 및 DB 연동
  dist/main.js
  jsconfig.json
  server/route.rest
  server/routes/columns.js
  src/app.js
  src/common/util.js
  src/components/header/Header.scss
  src/components/header/menu/Menu.js
  src/components/header/menu/Menu.scss
  src/components/main/Main.js
  src/components/main/column-container/Column/Column.js
  src/components/main/column-container/Column/Column.scss
  src/components/main/column-container/Column/card/Card.js
  src/components/main/column-container/Column/card/Card.scss
  src/components/main/column-container/Column/card/alert/Alert.js
  src/components/main/column-container/Column/card/alert/Alert.scss
  src/components/main/column-container/ColumnContainer.js
  src/stores/columnStore.js
  webpack.config.js
Labels: review-FE

#132 [team-07][BE][Jerry & 선을로] MySQL DB 연결 후 배포
  be/README.md
  be/todolist/build.gradle
  be/todolist/src/main/java/team07/todolist/controller/CardController.java
  be/todolist/src/main/java/team07/todolist/controller/ExceptionController.java
  be/todolist/src/main/java/team07/todolist/domain/ActivityLog.java
  be/todolist/src/main/java/team07/todolist/domain/Card.java
  be/todolist/src/main/java/team07/todolist/domain/Type.java
  be/todolist/src/main/java/team07/todolist/dto/RequestCard.java
  be/todolist/src/main/java/team07/todolist/dto/ResponseActivityLog.java
  be/todolist/src/main/java/team07/todolist/dto/ResponseCard.java
  be/todolist/src/main/java/team07/todolist/repository/ActivityLogRepository.java
  be/todolist/src/main/java/team07/todolist/repository/CardRepository.java
  be/todolist/src/main/java/team07/todolist/repository/DataBaseActivityLogRepository.java
  be/todolist/src/main/java/team07/todolist/repository/DataBaseCardRepository.java
  be/todolist/src/main/java/team07/todolist/repository/MemoryActivityLogRepository.java
  be/todolist/src/main/java/team07/todolist/repository/MemoryCardRepository.java
  be/todolist/src/main/java/team07/todolist/service/ActivityLogService.java
  be/todolist/src/main/java/team07/todolist/service/CardService.java
  be/todolist/src/main/resources/application.properties
  be/todolist/src/main/resources/sql/data.sql
  be/todolist/src/main/resources/sql/schema.sql
Labels: review-BE

#196 [Team-11 BE hoo & riako] TODO_LIST 최종 제출
  backend/src/main/java/com/hooria/todo/aop/ActivityAspect.java
  backend/src/main/java/com/hooria/todo/aop/ExcludeLogging.java
  backend/src/main/java/com/hooria/todo/controller/ActivityLogController.java
  backend/src/main/java/com/hooria/todo/controller/CardController.java
  backend/src/main/java/com/hooria/todo/domain/Device.java
  backend/src/main/java/com/hooria/todo/domain/Status.java
  backend/src/main/java/com/hooria/todo/dto/ActivityLogResponse.java
  backend/src/main/java/com/hooria/todo/dto/AddCardRequest.java
  backend/src/main/java/com/hooria/todo/dto/UpdateCardLayoutRequest.java
  backend/src/main/java/com/hooria/todo/dto/UpdateCardRequest.java
  backend/src/main/java/com/hooria/todo/error/CardRunTimeException.java
  backend/src/main/java/com/hooria/todo/error/ErrorCode.java
  backend/src/main/java/com/hooria/todo/error/ErrorResponse.java
  backend/src/main/java/com/hooria/todo/repository/CardRepository.java
  backend/src/main/java/com/hooria/todo/service/CardService.java
  backend/src/main/resources/logback.xml
  backend/src/main/resources/prod/data.sql
  backend/src/main/resources/prod/schema.sql
  backend/src/test/java/com/hooria/todo/controller/CardControllerMockTest.java
  backend/src/test/java/com/hooria/todo/repository/CardRepositoryTest.java
Labels: review-BE

#217 [team-12][BE] Swagger를 통한 문서 API 자동화 및 배포용 프로필 설정
  be/PRESENTATION.md
  be/build.gradle
  be/src/main/java/com/ijava/todolist/card/controller/CardController.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardCreateRequest.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardDeleteResponse.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardMoveRequest.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardMovedResponse.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardResponse.java
  be/src/main/java/com/ijava/todolist/card/controller/dto/CardUpdateRequest.java
  be/src/main/java/com/ijava/todolist/card/repository/JdbcCardRepository.java
  be/src/main/java/com/ijava/todolist/column/controller/ColumnController.java
  be/src/main/java/com/ijava/todolist/column/controller/dto/ColumnResponse.java
  be/src/main/java/com/ijava/todolist/config/SwaggerConfig.java
  be/src/main/java/com/ijava/todolist/history/controller/HistoryController.java
  be/src/main/java/com/ijava/todolist/history/controller/dto/HistoryResponse.java
  be/src/main/resources/application.yml
  be/src/main/resources/logback-spring.xml
  be/src/main/resources/logback.xml
Labels: review-BE

#198 [Team-05 BE nathan & 피오] Test 코드 추가
  backend/build.gradle
  backend/src/test/java/com/team05/todolist/controller/CardControllerTest.java
  backend/src/test/java/com/team05/todolist/controller/HomeControllerTest.java
Labels: review-BE

#222 [Team 17][BE] Todo List PR#4
  backend/README.md
  backend/diagram.drawio
  backend/src/main/java/com/codesquad/todolist/card/Card.java
  backend/src/main/java/com/codesquad/todolist/card/CardController.java
  backend/src/main/java/com/codesquad/todolist/card/CardRepository.java
  backend/src/main/java/com/codesquad/todolist/card/CardService.java
  backend/src/main/java/com/codesquad/todolist/card/dto/BundleResponse.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardCreateRequest.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardMoveRequest.java
  backend/src/main/java/com/codesquad/todolist/card/dto/CardUpdateRequest.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnRepository.java
  backend/src/main/java/com/codesquad/todolist/column/ColumnService.java
  backend/src/main/java/com/codesquad/todolist/config/WebMvcConfig.java
  backend/src/main/java/com/codesquad/todolist/exception/BusinessException.java
  backend/src/main/java/com/codesquad/todolist/exception/ErrorCode.java
  backend/src/main/java/com/codesquad/todolist/exception/ErrorResponse.java
  backend/src/main/java/com/codesquad/todolist/exception/GlobalExceptionHandler.java
  backend/src/main/java/com/codesquad/todolist/exception/NotFoundException.java
  backend/src/main/java/com/codesquad/todolist/history/HistoryRepository.java
  backend/src/main/java/com/codesquad/todolist/history/HistoryService.java
  backend/src/main/resources/application-local.properties
  backend/src/main/resources/application.properties
  backend/src/main/resources/data.sql
  backend/src/main/resources/schema.sql
  backend/src/test/java/com/codesquad/todolist/card/integration/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/integration/CardRepositoryTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardControllerTest.java
  backend/src/test/java/com/codesquad/todolist/card/unit/CardServiceTest.java
  backend/src/test/java/com/codesquad/todolist/history/integration/HistoryRepositoryTest.java
Labels: review-BE

#223 [데이먼 / 아더] Card, Column, History API 구현 및 피드백 적용
  BE/src/main/java/com/team26/todolist/TodolistApplication.java
  BE/src/main/java/com/team26/todolist/controller/CardController.java
  BE/src/main/java/com/team26/todolist/controller/ColumnController.java
  BE/src/main/java/com/team26/todolist/controller/HistoryController.java
  BE/src/main/java/com/team26/todolist/domain/Card.java
  BE/src/main/java/com/team26/todolist/domain/CardAction.java
  BE/src/main/java/com/team26/todolist/domain/CardStatus.java
  BE/src/main/java/com/team26/todolist/domain/Column.java
  BE/src/main/java/com/team26/todolist/domain/History.java
  BE/src/main/java/com/team26/todolist/domain/HistoryFactory.java
  BE/src/main/java/com/team26/todolist/dto/request/CardChangeLocationRequest.java
  BE/src/main/java/com/team26/todolist/dto/request/CardDeleteRequest.java
  BE/src/main/java/com/team26/todolist/dto/request/CardMoveRequest.java
  BE/src/main/java/com/team26/todolist/dto/request/CardRegistrationRequest.java
  BE/src/main/java/com/team26/todolist/dto/request/CardUpdateRequest.java
  BE/src/main/java/com/team26/todolist/dto/request/ColumnChangeOrderRequest.java
  BE/src/main/java/com/team26/todolist/dto/request/ColumnMoveRequest.java
  BE/src/main/java/com/team26/todolist/dto/response/CardResponse.java
  BE/src/main/java/com/team26/todolist/dto/response/ColumnResponse.java
  BE/src/main/java/com/team26/todolist/dto/response/HistoryResponse.java
  BE/src/main/java/com/team26/todolist/exception/EmptyCardStatusException.java
  BE/src/main/java/com/team26/todolist/repository/CardRepository.java
  BE/src/main/java/com/team26/todolist/repository/ColumnRepository.java
  BE/src/main/java/com/team26/todolist/repository/ColumnRepositoryImpl.java
  BE/src/main/java/com/team26/todolist/repository/HistoryRepository.java
  BE/src/main/java/com/team26/todolist/repository/HistoryRepositoryImpl.java
  BE/src/main/java/com/team26/todolist/service/CardService.java
  BE/src/main/java/com/team26/todolist/service/CardServiceJdbc.java
  BE/src/main/java/com/team26/todolist/service/CardServiceMock.java
  BE/src/main/java/com/team26/todolist/service/ColumnService.java
  BE/src/main/java/com/team26/todolist/service/ColumnServiceImpl.java
  BE/src/main/java/com/team26/todolist/service/HistoryService.java
  BE/src/main/java/com/team26/todolist/service/HistoryServiceImpl.java
  BE/src/main/java/com/team26/todolist/util/Constant.java
  BE/src/main/resources/sql/data.sql
  BE/src/main/resources/sql/schema.sql
Labels: review-BE

#201 [Team-11 iOS Eddy & Jason] TODO_LIST 최종 제출
  iOS/todo-list/todo-list.xcodeproj/project.pbxproj
  iOS/todo-list/todo-list/Model/Log.swift
  iOS/todo-list/todo-list/Resource/Assets.xcassets/Party Face Emoji.imageset/Contents.json
  iOS/todo-list/todo-list/Resource/Base.lproj/Main.storyboard
  iOS/todo-list/todo-list/UseCases/LogManager.swift
  iOS/todo-list/todo-list/View Model/LogViewModel.swift
  iOS/todo-list/todo-list/View/LogTableViewCell.swift
  iOS/todo-list/todo-list/ViewController/ActivityRecoderController.swift
  iOS/todo-list/todo-list/ViewController/LogViewController.swift
Labels: review-iOS

#230 [Team 34] [Front] Millie & Hoi
  .gitignore
  server/db.json
  src/index.html
  src/js/controller.js
  src/js/controller/controller.js
  src/js/index.js
  src/js/store/store.js
  src/js/utils/util.js
  src/js/views/cardDeleteView.js
  src/js/views/cardView.js
  src/js/views/columnsView.js
  src/js/views/dragView.js
  src/js/views/newCardView.js
  src/scss/components/_card.scss
  src/scss/components/_deleteAlert.scss
  src/scss/components/_drag.scss
  src/scss/main.scss
  src/scss/views/_todo.scss
Labels: review-FE

#200 [Team 21][FE] Todo List 2주차 PR2 Khan & Nick
  .gitignore
  FE/src/JS/drag-drop/drag-drop.js
  FE/src/JS/mok-data/mokData.json
  FE/src/JS/mok-data/sidebar-mokData.json
  FE/src/JS/sidebar/sidebar-controller.js
  FE/src/JS/sidebar/sidebar-model.js
  FE/src/JS/sidebar/sidebar-view.js
  FE/src/JS/todo/todo-controller.js
  FE/src/JS/todo/todo-model.js
  FE/src/JS/todo/todo-view-template.js
  FE/src/JS/todo/todo-view.js
  FE/src/style/header/header.scss
  FE/src/style/header/side-bar/sidebar.css
Labels: review-FE

#215 [team-30][FE] 협업 프로젝트 2주차 - 2
  .gitignore
  README.md
  server/db.json
  src/app.html
  src/app.js
  src/js/controller/MainController.js
  src/js/model/Store.js
  src/js/view/CardView.js
  src/js/view/ColumnView.js
  src/js/view/EmptyCardView.js
  src/js/view/historyView.js
  src/style/sideMenuBar.scss
  src/style/taskColumn.scss
  src/util/Util.js
Labels: review-FE

#204 [team-04] 루이 & Hwi - 2주차 마지막 PR입니다.
  BackEnd/src/main/java/todo/list/controller/CardController.java
  BackEnd/src/main/java/todo/list/domain/Action.java
  BackEnd/src/main/java/todo/list/domain/ActivityLog.java
  BackEnd/src/main/java/todo/list/domain/Author.java
  BackEnd/src/main/java/todo/list/domain/Card.java
  BackEnd/src/main/java/todo/list/domain/CardStatus.java
  BackEnd/src/main/java/todo/list/repository/ActivityLogRepository.java
  BackEnd/src/main/java/todo/list/repository/CardRepository.java
  BackEnd/src/main/java/todo/list/service/ActivityLogService.java
  BackEnd/src/main/java/todo/list/service/CardService.java
  BackEnd/src/main/java/todo/list/service/dto/CardModifyRequest.java
  BackEnd/src/main/java/todo/list/service/dto/CardMoveRequest.java
  BackEnd/src/main/java/todo/list/service/dto/CommandResultResponse.java
  BackEnd/src/main/resources/application.properties
  BackEnd/src/main/resources/data.sql
  BackEnd/src/main/resources/schema.sql
Labels: review-BE

#139 [iJava] Todo & 활동기록 목록조회
  ios/TodoApp/ActivityNetworkTests/ActivityNetworkTests.swift
  ios/TodoApp/TodoApp.xcodeproj/project.pbxproj
  ios/TodoApp/TodoApp.xcodeproj/xcshareddata/xcschemes/Development.xcscheme
  ios/TodoApp/TodoApp/Controllers/ActivityListViewController.swift
  ios/TodoApp/TodoApp/Controllers/Base.lproj/TodoListContainerViewController.storyboard
  ios/TodoApp/TodoApp/Controllers/TodoCreationViewController.storyboard
  ios/TodoApp/TodoApp/Controllers/TodoCreationViewController.swift
  ios/TodoApp/TodoApp/Controllers/TodoListContainerViewController.swift
  ios/TodoApp/TodoApp/Controllers/TodoListViewController.storyboard
  ios/TodoApp/TodoApp/Controllers/TodoListViewController.swift
  ios/TodoApp/TodoApp/Extensions/Alert.swift
  ios/TodoApp/TodoApp/Extensions/Logger+Extensions.swift
  ios/TodoApp/TodoApp/Extensions/NotificationCenter.swift
  ios/TodoApp/TodoApp/Models/ActivityRepository.swift
  ios/TodoApp/TodoApp/Models/ColumnRepository.swift
  ios/TodoApp/TodoApp/Models/Entity/Activity.swift
  ios/TodoApp/TodoApp/Models/Entity/Column.swift
  ios/TodoApp/TodoApp/Models/Entity/Todo.swift
  ios/TodoApp/TodoApp/Models/FieldFactory.swift
  ios/TodoApp/TodoApp/Models/TodoListViewModel.swift
  ios/TodoApp/TodoApp/Models/TodoRepository.swift
  ios/TodoApp/TodoApp/SceneDelegate.swift
  ios/TodoApp/TodoApp/Supporting Files/API.swift
  ios/TodoApp/TodoApp/Supporting Files/Info.plist
  ios/TodoApp/TodoApp/Views/ActivityCell.swift
  ios/TodoApp/TodoApp/Views/ToDoCell.swift
  ios/TodoApp/TodoApp/Views/TodoCell.swift
Labels: review-iOS

#216 [Team 07][iOS] 서버와 URLSession을 통한 네트워크 연결
  ios/ToDoListApp/ToDoListApp.xcodeproj/project.pbxproj
  ios/ToDoListApp/ToDoListApp/Constant/Constant.swift
  ios/ToDoListApp/ToDoListApp/Controller/ContainerViewController.swift
  ios/ToDoListApp/ToDoListApp/Controller/InspectorViewController.swift
  ios/ToDoListApp/ToDoListApp/Controller/KanbanColumnViewController.swift
  ios/ToDoListApp/ToDoListApp/Controller/MainViewController.swift
  ios/ToDoListApp/ToDoListApp/Controller/PopUpViewController.swift
  ios/ToDoListApp/ToDoListApp/Extension/CALayer+Extension.swift
  ios/ToDoListApp/ToDoListApp/Model/CardData.swift
  ios/ToDoListApp/ToDoListApp/Model/Delegate & DataSource/InspectorViewControllerDelegate.swift
  ios/ToDoListApp/ToDoListApp/Model/Delegate & DataSource/KanbanColumnViewControllerDelegate.swift
  ios/ToDoListApp/ToDoListApp/Model/Delegate & DataSource/KanbanTableViewDataSource.swift
  ios/ToDoListApp/ToDoListApp/Model/Delegate & DataSource/MainViewControllerDelegate.swift
  ios/ToDoListApp/ToDoListApp/Model/Delegate & DataSource/PopUpContentsTextViewDelegate.swift
  ios/ToDoListApp/ToDoListApp/Model/Entity/HTTPHeader.swift
  ios/ToDoListApp/ToDoListApp/Model/Entity/HTTPMethod.swift
  ios/ToDoListApp/ToDoListApp/Model/Entity/NetworkError.swift
  ios/ToDoListApp/ToDoListApp/Model/Entity/NetworkManger.swift
  ios/ToDoListApp/ToDoListApp/Model/Entity/ServerAPI.swift
  ios/ToDoListApp/ToDoListApp/Model/KanbanType.swift
  ios/ToDoListApp/ToDoListApp/View/InspectorTableViewCell.swift
  ios/ToDoListApp/ToDoListApp/View/KanbanTableViewCell.swift
  ios/ToDoListApp/ToDoListApp/View/PopUpView.swift
  ios/ToDoListApp/ToDoListApp/View/TableTitleView.swift
  ios/ToDoListApp/ToDoListApp/View/TitleView.swift
Labels: review-iOS

#195 [Team-02][BE] 활동 내역 등록 & 조회, 리팩토링
  backend/todolist/README.md
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardByStatus.java
  backend/todolist/src/main/java/kr/codesquad/todolist/card/CardService.java
  backend/todolist/src/main/java/kr/codesquad/todolist/controller/CardApiController.java
  backend/todolist/src/main/java/kr/codesquad/todolist/controller/HistoryDTO.java
  backend/todolist/src/main/java/kr/codesquad/todolist/controller/request/CardRequestDto.java
  backend/todolist/src/main/java/kr/codesquad/todolist/controller/response/CardResponseDto.java
  backend/todolist/src/main/java/kr/codesquad/todolist/dao/CardDao.java
  backend/todolist/src/main/java/kr/codesquad/todolist/dao/HistoryDao.java
  backend/todolist/src/main/java/kr/codesquad/todolist/domain/Card.java
  backend/todolist/src/main/java/kr/codesquad/todolist/domain/History.java
  backend/todolist/src/main/java/kr/codesquad/todolist/service/CardService.java
  backend/todolist/src/main/java/kr/codesquad/todolist/service/CardStatusNumber.java
  backend/todolist/src/main/java/kr/codesquad/todolist/service/HistoryService.java
  backend/todolist/src/test/java/kr/codesquad/todolist/service/CardServiceTest.java
Labels: review-BE

#219 [Team-25] [FE] TODO LIST 2주차 두번째 PR
  .gitignore
  Procfile
  db.json
  package-lock.json
  package.json
  server.js
  src/client/js/api/index.js
  src/client/js/api/taskApi.js
  src/client/js/components/Action.js
  src/client/js/components/ActionLayer.js
  src/client/js/components/Alert.js
  src/client/js/components/Card.js
  src/client/js/components/Column.js
  src/client/js/components/Header.js
  src/client/js/components/InputCard.js
  src/client/js/constants/index.js
  src/client/js/render/index.js
  src/client/js/store/actionStore.js
  src/client/js/store/taskStore.js
  src/client/js/utils/index.js
  src/client/style/style.scss
  src/server/init.js
  src/server/middleware.js
  webpack.config.cjs
Labels: review-FE

#236 [team-16][iOS] 2주차 네트워크 계층 구성 및 POST 요청/응답 구현
  todo-list-ios/TODOList/TODOList.xcodeproj/project.pbxproj
  todo-list-ios/TODOList/TODOList/Controllers/MemoCanvasViewController.swift
  todo-list-ios/TODOList/TODOList/Controllers/MemoContainerType.swift
  todo-list-ios/TODOList/TODOList/Controllers/MemoContainerViewController.swift
  todo-list-ios/TODOList/TODOList/Controllers/PopupViewController.swift
  todo-list-ios/TODOList/TODOList/Data/Network/HTTPRequestHandler.swift
  todo-list-ios/TODOList/TODOList/Data/Network/Model/CommonResponseType.swift
  todo-list-ios/TODOList/TODOList/Data/Network/Model/MemoPostData.swift
  todo-list-ios/TODOList/TODOList/Data/Network/Model/MemoResponse.swift
  todo-list-ios/TODOList/TODOList/Delegates/MemoContainerViewDelegate.swift
  todo-list-ios/TODOList/TODOList/Delegates/PopupCardViewDelegate.swift
  todo-list-ios/TODOList/TODOList/Delegates/PopupViewDelegate.swift
  todo-list-ios/TODOList/TODOList/Domain/Entities/HistoryEntity.swift
  todo-list-ios/TODOList/TODOList/Domain/Entities/MemoEntity.swift
  todo-list-ios/TODOList/TODOList/Domain/MemoStatus.swift
  todo-list-ios/TODOList/TODOList/Domain/UseCases/HistoryUseCase.swift
  todo-list-ios/TODOList/TODOList/Domain/UseCases/MemoUseCase.swift
  todo-list-ios/TODOList/TODOList/Models/Memo/Memo.swift
  todo-list-ios/TODOList/TODOList/Models/Memo/MemoStatus.swift
  todo-list-ios/TODOList/TODOList/Models/MemoManager.swift
  todo-list-ios/TODOList/TODOList/Models/Protocols/RequestEntityConvertible.swift
  todo-list-ios/TODOList/TODOList/Network/EndPoint.swift
  todo-list-ios/TODOList/TODOList/Network/Entities/CommonResponseType.swift
  todo-list-ios/TODOList/TODOList/Network/Entities/MemoRequest.swift
  todo-list-ios/TODOList/TODOList/Network/Entities/MemoResponse.swift
  todo-list-ios/TODOList/TODOList/Network/JSONHandler.swift
  todo-list-ios/TODOList/TODOList/Network/NetworkHandler.swift
  todo-list-ios/TODOList/TODOList/Resources/sample.json
  todo-list-ios/TODOList/TODOList/Views/Memo/MemoContainerView.swift
  todo-list-ios/TODOList/TODOList/Views/Memo/PopupCardView.swift
Labels: review-iOS

#234 [Team-23] 스토어 에러 및 이벤트
  .gitignore
  .idea/workspace.xml
  README.md
  app.ts
  components/TodoCard.ts
  components/TodoForm.ts
  components/TodoList.ts
  core/DTOs/add.dto.ts
  core/DTOs/delete.dto.ts
  core/DTOs/move.dto.ts
  core/DTOs/select.dto.ts
  core/DTOs/update.dto.ts
  core/Eventhandler.ts
  core/Node.ts
  core/Observer.ts
  core/Store.ts
  core/View.ts
  express-server/static/db.json
  index.html
  package.json
  readme.md
  styles/scss/_column.scss
  styles/scss/_reset.css
  styles/scss/_shared.scss
  styles/scss/index.css
  tsconfig.json
  types.ts
  utils.ts
  webpack.common.js
  webpack.dev.js
  yarn.lock
Labels: review-FE

#194 [team-08][BE] todo-list 2주차 #4
  be/src/main/java/todolist/controller/CardController.java
  be/src/main/java/todolist/controller/EventController.java
  be/src/main/java/todolist/domain/card/Card.java
  be/src/main/java/todolist/domain/card/Section.java
  be/src/main/java/todolist/domain/event/Action.java
  be/src/main/java/todolist/domain/event/Event.java
  be/src/main/java/todolist/dto/card/RequestCardDto.java
  be/src/main/java/todolist/dto/card/ResponseCardsDto.java
  be/src/main/java/todolist/dto/event/RequestEventDto.java
  be/src/main/java/todolist/dto/event/ResponseEventDto.java
  be/src/main/java/todolist/service/CardService.java
  be/src/main/java/todolist/service/EventService.java
  be/src/test/java/todolist/service/CardServiceTest.java
Labels: review-BE

#233 [team-06] [땃쥐 & Shine] Todo-list 4차 코드리뷰 요청
  BE/API_Detail.md
  BE/build.gradle
  BE/src/main/java/codesquad/todo/domain/history/History.java
  BE/src/main/java/codesquad/todo/domain/history/JdbcTemplateHistoryRepository.java
  BE/src/main/java/codesquad/todo/domain/user/JdbcTemplateUserRepository.java
  BE/src/main/java/codesquad/todo/domain/user/User.java
  BE/src/main/java/codesquad/todo/domain/work/JdbcTemplateWorkRepository.java
  BE/src/main/java/codesquad/todo/domain/work/Work.java
  BE/src/main/java/codesquad/todo/service/WorkService.java
  BE/src/main/resources/application-online.properties
  BE/src/main/resources/application.properties
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
  BE/src/test/java/codesquad/todo/domain/work/JdbcTemplateWorkRepositoryTest.java
  BE/src/test/java/codesquad/todo/service/WorkServiceTest.java
Labels: review-BE
